### ISSUE TITLE
internal docker dns ndots:0 not supported by go

### ISSUE THREAD

**Issue by pbnjay** [docker-library/golang#109]
If you use a hostname/alias without dots, the dns resolution fails because go's netdns replaces docker's generated /etc/resolv.conf `ndots:0` with `ndots:1`  (golang/go#15419)

So this image is highly broken in current docker without backporting this patch:
    https://go-review.googlesource.com/#/c/24901/

Or at the very least patching the single line in `net/dnsconfig_unix.go` with `s/n = 1/n = 0/`

**Comment by mraxus** [comment]
I spent half a weekend on a DNS resolution problem before I got some help to lead me in the right direction. I assume my issue is related to this.

I created a repo to showcase this issue, for anyone wanting to see: https://github.com/mraxus/mystery-golang-alpine

Also, the working solution I came up with: https://github.com/mraxus/mystery-golang-alpine/pull/3

**Comment by tianon** [comment]
Ah, according to https://github.com/golang/go/commit/2f73fe7a0db269dcbe51e372809032fa52b8c68c, the commit which fixes this in Go was included in both Go 1.8 and Go 1.9. :sweat_smile:

**Comment by mraxus** [comment]
@tianon: As it turns out, search domains, configured on our corporate network was the real problem here. For some reason, `alpine` containers are affected by this, but not the `golang` containers. Luckily, it's configurable in `docker-compose.yml`. See https://github.com/mraxus/mystery-golang-alpine/pull/4

**Comment by tianon** [comment]
Nice, glad you got it figured out! :+1:

I'm going to close this since the original issue should be fixed in Go 1.8+. :+1:
