### ISSUE TITLE
can't load package: /go/src/app/api.go:15:5: local import "./segments" in non-local package #10

### ISSUE THREAD

**Issue by aep** [docker-library/golang#120]
````
cat api.go
package main
import (
    "./segments"
)
````

main is obviously a local package, so this should work. Not sure what breaks this, since go get works fine outside docker. It's probably the magic "src" in  /go/src/ which invokes mystical gopath madness. 
Is the move to /src/ in onbuild intentional?

**Comment by yosifkit** [comment]
The `COPY` to `/go/src/` is intentional in the onbuild image.  Maybe you should not use the onbuild image and just add commands to your own Dockerfile that mirror how you build locally.

**Comment by aep** [comment]
yup, no big deal for me. was just thinking that reporting broken local includes is worth a report maybe.

**Comment by mikeifomin** [comment]
So sad :(
