### ISSUE TITLE
Add Go 1.8 Beta 1

### ISSUE THREAD

**Issue by broady** [docker-library/golang#122]
https://golang.org/dl/#go1.8beta1

**Comment by tianon** [comment]
Initial add in https://github.com/docker-library/golang/commit/7319cccdf0c2b8cbcb4ea214f310e8d15fe5c1dd, minor patch fix in https://github.com/docker-library/golang/commit/7a5e33ec522b17dffa51c2763610a2967475529d and we're ready to rock and roll! :metal:

(https://travis-ci.org/docker-library/golang/builds/180415932)

Thanks @broady! :heart: :heart: :heart:

**Comment by broady** [comment]
awwww, yeah!

**Comment by tianon** [comment]
Final step: https://github.com/docker-library/official-images/pull/2408
