### ISSUE TITLE
default $GOPATH environment variable

### ISSUE THREAD

**Issue by zchee** [docker-library/golang#129]
Hi, thanks for maintaining the good base image for Go.

This issue is a just proposal.

I think you already know, go1.8 has been implemented default `$GOPATH` to `$HOME/go`(on Unix).
https://github.com/golang/go/commit/dc4a815d100b82643656ec88fd9fa8e7c705ebba

I know that is not language spec, and it can be changed arbitrarily by the users.
However, As the typical install go toolchain directory is `/usr/local/go`(on Unix), I think `GOPATH=$HOME/go` will also be a defacto directory path for `$GOPATH` to some extent.
But, current official `golang` docker image sets the `$GOPATH` to `/go`, which is not `$HOME/go` even if the user is root. (in case of not set `--user` flag)

I do not think it is absolutely necessary, but might be `ENV GOPATH $HOME/go` is a better setting than using a `golang` image specific setting.
But also that change might be no backward compatibility.

What do you think about it?

**Comment by tianon** [comment]
Backwards compatibility is definitely a major concern with changing that value, but also, we don't/can't really know the right value for `$HOME` ahead of time, so I still think our static value of `/go` makes sense -- the exact path inside the image shouldn't matter too much, in the end.

**Comment by zchee** [comment]
@tianon Thanks for polite reply.
I understand opinion and agreed. I am glad to understand the policy of dockerfile clearly.

Thanks again for maintaining base image!
Close.
