### ISSUE TITLE
upgrade to alpine 3.5

### ISSUE THREAD

**Issue by vikstrous** [docker-library/golang#130]
There's a new alpine release and base image. Please upgrade golang images to alpine 3.5.

**Comment by tianon** [comment]
Once "alpine:latest" is updated, I'm +1.

**Comment by tianon** [comment]
(It's currently still 3.4)

**Comment by justincormack** [comment]
@tianon alpine `latest` is now `3.5` see https://github.com/gliderlabs/docker-alpine/commit/6289beac7589fa87a9f64413e3fc54fbecebb097

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/commit/c6651d4c0e9bfaabd474539157d6a4b6bb4970c2 is actually the commit which updated the tag on the Hub :smile:

Will go do a bump and build test!
