### ISSUE TITLE
Release cycle, when will 1.8rc1 make it to Docker Hub?

### ISSUE THREAD

**Issue by VojtechVitek** [docker-library/golang#137]
Hi,
as I can see, the 1.8rc1 was already committed at b819b526131d44c03f02942816f616067d389037. 

When can we expect 1.8rc1 reaching Docker Hub? What is the release cycle of this repo?

Thanks,
 Vojtech

**Comment by tianon** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/golang" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/golang), especially [PRs with the "library/golang" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fgolang). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

This particular bump is over in https://github.com/docker-library/official-images/pull/2530. :+1:

**Comment by VojtechVitek** [comment]
Thanks!
