### ISSUE TITLE
binary built by this image run with a panic 

### ISSUE THREAD

**Issue by baoyangc** [docker-library/golang#138]
2017/01/23 17:28:37 mysql.go:49: [PANIC] cannot find Asia/shanghai in zip file /usr/local/go/lib/time/zoneinfo.zip
[stack]:
    3   /gopath/src/pangu/models/dao/mysql.go:49
            pangu/models/dao.init.1
    2   /gopath/src/pangu/models/dao/mysql.go:216
            pangu/models/dao.init
    1   /gopath/src/pangu/handlers/contract/sts.go:132
            pangu/handlers/contract.init
    0   /usr/src/myapp/main.go:25
            main.init

as my code set an DSN with timezone Asia/shanghai

**Comment by yosifkit** [comment]
Looks like it needs to be capitalized, `Asia/Shanghai`.

**Comment by yosifkit** [comment]
As far as I can tell, this was fixed.
