### ISSUE TITLE
Add Git to nanoserver image?

### ISSUE THREAD

**Issue by StefanScherer** [docker-library/golang#140]
I recently tried to build docker/distribution in a nanoserver container. 

The golang nanoserver image does not contain Git, only the windowsservercore variant. 
I've installed it in my Dockerfile like this: 
https://github.com/StefanScherer/dockerfiles-windows/blob/master/registry/build/Dockerfile#L8-L16

Is it worth to send a PR? 😀

**Comment by yosifkit** [comment]
I would call this a duplicate of #119; we consider nanoserver [similar to the `slim` variant](https://github.com/docker-library/golang/blob/da6e73b4fa5b3094a23202cca088dd11b74ed110/1.8/windows/nanoserver/Dockerfile#L6-L7).

**Comment by StefanScherer** [comment]
OK, I understand and haven't seen that comment in the Dockerfile. So I close this issue and leave the Git install commands in my Dockerfile also as an example how to do it in nanoserver.
