### ISSUE TITLE
/usr/local/bin/go-wrapper: 89: exec: app: not found

### ISSUE THREAD

**Issue by g3gurung** [docker-library/golang#141]
I have used golang 1.8 onbuild docker file. 

`$ docker build -t my-app .` 
works fine but
`$ docker run --publish 8086:8086 --name test --rm my-app` 
gives this-> **/usr/local/bin/go-wrapper: 89: exec: app: not found**

**Comment by nathany** [comment]
possibly related to #90?

**Comment by tianon** [comment]
Yeah, this sounds like your `package main` isn't at the top-level of your repository (ie, where your `Dockerfile` is) -- I'd recommend not using the `onbuild` variant and instead just writing the few lines necessary for building your application in a container (as described over in #90). :+1:

**Comment by g3gurung** [comment]
Yes, so I used this
```

FROM golang:1.6

WORKDIR /go/src/app
COPY . .

RUN go install -v

CMD ["app"]
```

but there is still some error like below if i do->

```
$ docker build -t my-app .
**Sending build context to Docker daemon   126 kB
Step 1/5 : FROM golang:1.6
 ---> 63330314bb46
Step 2/5 : WORKDIR /go/src/app
 ---> Using cache
 ---> bdd3ec45a955
Step 3/5 : COPY . .
 ---> Using cache
 ---> 60f68469748b
Step 4/5 : RUN go install -v
 ---> Running in 13a72a6960a1
main.go:12:2: cannot find package "github.com/justinas/alice" in any of:
	/usr/local/go/src/github.com/justinas/alice (from $GOROOT)
	/go/src/github.com/justinas/alice (from $GOPATH)**
```

**Comment by tianon** [comment]
Which directory within your application holds `package main`?

**Comment by g3gurung** [comment]
`/Users/pratakshagurung/goProjects/src/github.com/keyAPI`

this **keyAPI** contains Dockerfile and main.go(which is a package main)

**Comment by g3gurung** [comment]
Well it was pretty straight forward I tried to write my own..... and this worked->

```
FROM golang:latest

# Copy the local package files to the container’s workspace.
ADD . /go/src/github.com/keyAPI

# Install the  dependencies
RUN go get gopkg.in/pg.v4
RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/justinas/alice
RUN go get github.com/satori/go.uuid

# Install api binary globally within container 
RUN go install github.com/keyAPI

# Set binary as entrypoint
ENTRYPOINT /go/bin/keyAPI

# Expose default port (8086)
EXPOSE 8086 
```

**Comment by yosifkit** [comment]
Looks like this is fixed!  Feel free to comment if you feel this was closed in error.
