### ISSUE TITLE
image sizes: alpine

### ISSUE THREAD

**Issue by mbana** [docker-library/golang#142]
i've wrote a bunch of bash scripts to fetch, build, run and list the sizes of all the tagged images.
i'm trying to be scientific about this, and eventually use the smallest image.
i'm sort of limited to what the dockerhub api offers so not all tags get built.
if anyone has any ideas or would like to add to it, you're more than welcome:

```sh
hello world from: golang_1.4-alpine:latest
...
hello world from: golang_1.6rc2-alpine:latest
...
golang_1.4-alpine	latest	f687c7a9c8fd	5 hours	143MB
...
golang_1.6beta1-alpine	latest	893cc010d166	5 hours	282MB
```

https://github.com/mbana/golang-docker-alpine-bench

**Comment by tianon** [comment]
Closing, since this doesn't appear to be an issue with the `golang` image directly.

For up-to-date information about the size and contents of the officially built artifacts of this image, see https://github.com/docker-library/repo-info/tree/master/repos/golang.
