### ISSUE TITLE
drop wheezy images for newer go versions

### ISSUE THREAD

**Issue by yosifkit** [docker-library/golang#143]
I propose we drop the wheezy images;  maybe even as soon as the pending `1.8` release.

It seems that the reason we kept `wheezy` was to have an image based on Debian stable: https://github.com/docker-library/golang/pull/21#issuecomment-58589491.

**Comment by tianon** [comment]
+1, let it die in a rolling manner

**Comment by tianon** [comment]
If we're being totally honest, I'd even be +1 to moving `golang:1.8` over to `stretch`, but that's a totally separate conversation, and possibly even a bit premature (since it's only frozen, not actually stable / security-supported yet).
