### ISSUE TITLE
exec patch -p2 -i /no-pic.patch is No such file or directoryinternal/ld/lib.go

### ISSUE THREAD

**Issue by huangmeng4520** [docker-library/golang#150]
/usr/local/go/src # patch -p2 -i /no-pic.patch 
patching file cmd/link/internal/ld/lib.go
': No such file or directoryinternal/ld/lib.go
/usr/local/go/src #

**Comment by tianon** [comment]
Sorry for the delay -- if this is while building the image, we can't reproduce (see https://travis-ci.org/docker-library/golang/branches).
