### ISSUE TITLE
Update armhf builds

### ISSUE THREAD

**Issue by luckcolors** [docker-library/golang#151]
Last build in https://hub.docker.com/r/armhf/ is from 1 year ago.
Please make ones for later golang versions such as 1.8, 1.7.5.

**Comment by cceckman** [comment]
The documentation at the provided link indicates armhf is deprecated in favor of the more-specific variants, e.g. https://hub.docker.com/r/arm32v7/golang/.

Looks like https://github.com/docker-library/official-images#architectures-other-than-amd64 has more info.

(I'm not an admin / expert, just wanted to share what I found in my own investigation :-) )

**Comment by tianon** [comment]
Indeed -- @cceckman is correct. :+1: :heart:
