### ISSUE TITLE
Failed to build a gRPC service as docker won't find the gengo package

### ISSUE THREAD

**Issue by dkassab** [docker-library/golang#154]
I'm trying to dockerize a gRPC service using the following Dockerfile
```
FROM golang:1.7

RUN mkdir -p /go/src/app
WORKDIR /go/src/app
COPY . /vendor/github.com/gengo/grpc-gateway/third_party/googleapis/google/api
COPY . /go/src/app
RUN go install -v
CMD ["app"]
```

The service is a gRPC service: https://github.com/dkassab/go-calc-service/blob/master/server/server.go

The error message I'm getting is:
```
Step 6/7 : RUN go install -v
 ---> Running in a83cdac70735
vendor/github.com/dkassab/go-calc-service/calc/calc.pb.go:26:8: cannot find package "github.com/gengo/grpc-gateway/third_party/googleapis/google/api" in any of:
	/go/src/app/vendor/github.com/gengo/grpc-gateway/third_party/googleapis/google/api (vendor tree)
	/usr/local/go/src/github.com/gengo/grpc-gateway/third_party/googleapis/google/api (from $GOROOT)
	/go/src/github.com/gengo/grpc-gateway/third_party/googleapis/google/api (from $GOPATH)
The command '/bin/sh -c go install -v' returned a non-zero code: 1
```
Even though I'm specifically copying the gengo package into the container.

**Comment by tianon** [comment]
Does it work if you do something like this?
```dockerfile
FROM golang:1.7

WORKDIR /go/src/github.com/dkassab/go-calc-service/server
COPY . .
RUN go get -v
CMD ["server"]
```

I think the problem is that `.` does not contain the package your service needs, but rather contains your package (so we need to use `go get` to download the necessary dependencies after putting our own package in the proper place).

**Comment by dkassab** [comment]
When I build using the Dockerfile you provided, I get:
```
Step 4/5 : RUN go get -v
 ---> Running in 4fe804f3b10d
github.com/gengo/grpc-gateway (download)
package github.com/gengo/grpc-gateway/third_party/googleapis/google/api: no buildable Go source files in /go/src/github.com/gengo/grpc-gateway/third_party/googleapis/google/api
The command '/bin/sh -c go get -v' returned a non-zero code: 1
```

**Comment by tianon** [comment]
Ah, that looks like it's due to the fact that https://github.com/grpc-ecosystem/grpc-gateway/tree/7980281cb6ac1dacf3f0025c53870c817c1c9511/third_party/googleapis/google/api only has the `.proto` files, and not the generated Go -- not sure how to fix that (or what's going on there). :confused:

**Comment by dkassab** [comment]
@tianon It looks like gengo is deprecated and replaced with https://godoc.org/google.golang.org/genproto/googleapis/api/annotations
re-running protoc to re-generate the stubs fixed the problems. 

Thank you for your help :)
