### ISSUE TITLE
How set interactive mode and logs

### ISSUE THREAD

**Issue by Limoli** [docker-library/golang#167]
I am Docker beginner and I am using your image `golang:1.8.3-alpine`.
If I run the docker container in interactive mode (-it) I see nothing.
The application is pending without print out any logs even if my application prints on standard out buffer a log for each request.
Is it caused by `go-wrapper`?
Could I access to Alpine OS in interactive mode?
Thank you in advance for your help.

**Comment by tianon** [comment]
If you adjust your command to `sh`, it should start a shell instead of your application:
```console
$ docker run -it --rm <your-image> sh
```
