### ISSUE TITLE
What happened to the old tags?

### ISSUE THREAD

**Issue by bboreham** [docker-library/golang#177]
We had some unit tests that were happily rolling inside `docker run golang:1.8.0` , but today it's gone.

If this was intentional, where should we look out for announcements of old tags being removed?

**Comment by tianon** [comment]
I can't seem to reproduce: :confused: (perhaps Docker Hub had a temporary hiccup?)
```console
$ docker pull golang:1.8.0
1.8.0: Pulling from library/golang
6d827a3ef358: Already exists 
2726297beaf1: Already exists 
7d27bd3d7fec: Already exists 
62ace0d726fe: Already exists 
fc75fef0061c: Pull complete 
79830f04078a: Pull complete 
ef366adb749f: Pull complete 
Digest: sha256:70317de915e3414b6bd8e1a0f714d6c4e2d11262abf6815fe9895495a1b3d635
Status: Downloaded newer image for golang:1.8.0
```

**Comment by bboreham** [comment]
Aha, yes, indeed subsequent of our CI builds have managed to download it.  This is what the failure looked like in the logs:

```
Unable to find image 'golang:1.8.0' locally
1.8.0: Pulling from library/golang














Pulling repository docker.io/library/golang
Tag 1.8.0 not found in repository docker.io/library/golang
```

Apologies for jumping to conclusions.
