### ISSUE TITLE
No image for golang 1.9 and alpine 3.5

### ISSUE THREAD

**Issue by javier-sanz** [docker-library/golang#178]
Hello guys. 

I was going to update our build system to go 1.9.1 and I've seen that there is no version using alpine 3.5. Only alpine version 3.6 is available. It is any particular reason for that? I have googled it but I haven't found an answer. 

Thanks

**Comment by yosifkit** [comment]
Since the introduction of the golang 1.9 Alpine image it has been based on Alpine 3.6 (https://github.com/docker-library/golang/pull/165). Golang 1.9 was released after Alpine 3.6 came out so there was no reason to make it based on an already old version of Alpine.

**Comment by javier-sanz** [comment]
Thanks @yosifkit for your answer.
