### ISSUE TITLE
Several images not getting built

### ISSUE THREAD

**Issue by ry4nz** [docker-library/golang#179]
Checking the Jenkins log, there are several images not getting built.

```
skipping "golang:1.9.1-alpine3.6" (due to architecture "s390x"; only "amd64" supported)
skipping "golang:1.9.1-windowsservercore" (due to architecture "s390x"; only "windows-amd64" supported)
skipping "golang:1.9.1-nanoserver" (due to architecture "s390x"; only "windows-amd64" supported)
skipping "golang:1.8.4-alpine3.6" (due to architecture "s390x"; only "amd64" supported)
skipping "golang:1.8.4-alpine3.5" (due to architecture "s390x"; only "amd64" supported)
skipping "golang:1.8.4-windowsservercore" (due to architecture "s390x"; only "windows-amd64" supported)
skipping "golang:1.8.4-nanoserver" (due to architecture "s390x"; only "windows-amd64" supported)
```

Images `golang:1.9.1-alpine3.6` `golang:1.8.4-alpine3.6` `golang:1.8.4-alpine3.6` should be built.

**Comment by tianon** [comment]
You're looking at the logs specifically for the `s390x` architecture, which Alpine doesn't currently support (https://github.com/gliderlabs/docker-alpine/issues/304), and Windows definitely doesn't support.

See https://doi-janky.infosiftr.net/job/multiarch/job/windows-amd64/job/golang/lastCompletedBuild/console for where the last `nanoserver` and `windowsservercore` builds were successfully processed, and https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/lastCompletedBuild/console for the `alpine*` tags.
