### ISSUE TITLE
Go 1.9.2 tags

### ISSUE THREAD

**Issue by pierrre** [docker-library/golang#183]
Hello,

Go 1.9.2 has been released, and I can see the update in the image:
https://github.com/docker-library/golang/commit/cffcff7fce7f6b6b5c82fc8f7b3331a10590a661

However I don't see the tags:
https://hub.docker.com/_/golang/

From my build:
```
Step 1/15 : FROM golang:1.9.2-alpine3.6 as builder
manifest for golang:1.9.2-alpine3.6 not found
```

Is there a problem ?

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/golang" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/golang), especially [PRs with the "library/golang" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fgolang). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).
>
> \- https://github.com/docker-library/golang/blob/a2400b0dbafdbb55e7ee1cbbc02b362c3a909ca1/README.md#about-this-repo

Done: https://github.com/docker-library/official-images/pull/3629

**Comment by pierrre** [comment]
Thank you ! 👍
