### ISSUE TITLE
Error getting dependency

### ISSUE THREAD

**Issue by josecordaz** [docker-library/golang#188]
When I run 

`go get honnef.co/go/tools/cmd/unused`

Fails: 

`package honnef.co/go/tools/cmd/unused: unrecognized import path "honnef.co/go/tools/cmd/unused" (https fetch: Get https://honnef.co/go/tools/cmd/unused?go-get=1: x509: certificate signed by unknown authority)`

**Comment by yosifkit** [comment]
It seems that you are using the alpine based image.  You need to install things like ca-certificates or git if you need them:

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Comment by josecordaz** [comment]
I am using golang:1.9.2-stretch, I already tried installing certificates like this : https://www.codingmerc.com/blog/add-lets-encrypt-root-certificate-linux/
but it doesn't fix the problem

**Comment by yosifkit** [comment]
I am not able to reproduce:

```console
docker run -it --rm golang:1.9.2-stretch
root@24aa8b8ff8ad:/go# go get honnef.co/go/tools/cmd/unused
root@24aa8b8ff8ad:/go# ls src/honnef.co/go/tools/
LICENSE    cmd	       functions  internal  ssa		  unused
README.md  deprecated  gcsizes	  lint	    staticcheck   version
callgraph  errcheck    images	  simple    structlayout
root@24aa8b8ff8ad:/go# ls -l bin/                          
total 6936
-rwxr-xr-x 1 root root 7102292 Dec  1 20:40 unused
root@24aa8b8ff8ad:/go# unused -h
Usage of unused:
	unused [flags] # runs on package in current directory
	unused [flags] packages
	unused [flags] directory
	unused [flags] files... # must be a single package
Flags:
  -consts
    	Report unused constants (default true)
  -debug file
    	Write a debug graph to file. Existing files will be overwritten.
  -exported
    	Treat arguments as a program and report unused exported identifiers
  -f format
    	Output format (valid choices are 'text' and 'json') (default "text")
  -fields
    	Report unused fields (default true)
  -funcs
    	Report unused functions and methods (default true)
  -go version
    	Target Go version in the format '1.x' (default 1.9)
  -ignore string
    	Space separated list of checks to ignore, in the following format: 'import/path/file.go:Check1,Check2,...' Both the import path and file name sections support globbing, e.g. 'os/exec/*_test.go'
  -min_confidence float
    	Deprecated; use -ignore instead
  -reflect
    	Consider identifiers as used when it's likely they'll be accessed via reflection (default true)
  -show-ignored
    	Don't filter ignored problems
  -tags build tags
    	List of build tags
  -tests
    	Include tests (default true)
  -types
    	Report unused types (default true)
  -vars
    	Report unused variables (default true)
  -version
    	Print version and exit
```

**Comment by josecordaz** [comment]
It's weird: 

`docker run -it --rm golang:1.9.2-stretch
root@f789ad04dca7:/go# go get honnef.co/go/tools/cmd/unused
package honnef.co/go/tools/cmd/unused: unrecognized import path "honnef.co/go/tools/cmd/unused" (https fetch: Get https://honnef.co/go/tools/cmd/unused?go-get=1: x509: certificate signed by unknown authority)
root@f789ad04dca7:/go#`

**Comment by tianon** [comment]
Is your Docker system's time in sync? Sometimes that'll exhibit as
certificate errors.

**Comment by josecordaz** [comment]
How could I check that? @tianon
