### ISSUE TITLE
build and runtime environment results in a huge image

### ISSUE THREAD

**Issue by kaihendry** [docker-library/golang#194]
I moved my lambda function to a Dockerfile and I'm stunned how large the resulting 400M image is:

```
FROM golang:alpine

RUN apk --no-cache add git

ADD . /go/src/github.com/Example/pls3
WORKDIR /go/src/github.com/Example/pls3/cmd/pls3
RUN go get && go install -v

ARG COMMIT
ENV COMMIT ${COMMIT}

ENTRYPOINT ["/go/bin/pls3"]
```

I assuming it's because of all the deps. Is there a simpler approach of just packaging the amd64 static binary? Or is there something I am missing?

**Comment by jsegura** [comment]
You should try multi-stage builds. Your `Dockerfile` will look like:
```
FROM golang:alpine as build

RUN apk --no-cache add git

ADD . /go/src/github.com/Example/pls3
WORKDIR /go/src/github.com/Example/pls3/cmd/pls3
RUN go get && go install -v

FROM alpine:latest

WORKDIR /
COPY --from=build /go/bin/pls3

ARG COMMIT
ENV COMMIT ${COMMIT}

ENTRYPOINT ["/pls3"]
```

**Comment by kaihendry** [comment]
Cool! A ~5 megabyte image!

However, I hit this `x509: failed to load system roots and no roots provided, ` when I try http.Get a URL with that. Bit uncertain how to fix this after reading https://github.com/docker-library/golang/issues/96 .. any ideas?

Btw the `COPY --from=build /go/bin/pls3 /pls3` needed a final argument.

**Comment by jsegura** [comment]
oh yes, you are right. I missed the argument.

For the ca certificates, they are not installed by default on alpine image. You should execute `apk --no-cache add ca-certificates && update-ca-certificates` on the final image.

Let's recap:

```
FROM golang:alpine as build

RUN apk --no-cache add git

ADD . /go/src/github.com/Example/pls3
WORKDIR /go/src/github.com/Example/pls3/cmd/pls3
RUN go get && go install -v

FROM alpine:latest

WORKDIR /
COPY --from=build /go/bin/pls3 /pls3
RUN apk --no-cache add ca-certificates && update-ca-certificates

ARG COMMIT
ENV COMMIT ${COMMIT}

ENTRYPOINT ["/pls3"]

```

**Comment by kaihendry** [comment]
Thank you, happy with the result. Thank you very much for your help and guidance. :gift:
