### ISSUE TITLE
1.10 Beta2 is out

### ISSUE THREAD

**Issue by jerome-laforge** [docker-library/golang#199]
Hello,
It would be great to update golang's docker to 1.10 Beta2.
cf. https://groups.google.com/forum/#!topic/golang-dev/1pw2h62nU-A
Thx in adv

**Comment by ImreSamu** [comment]
see https://github.com/docker-library/golang/commit/d4c78f49b7e192e064909a40d7c3e198887fc68f

**Comment by jerome-laforge** [comment]
But it seems no take into account on docker side:
https://hub.docker.com/_/golang/ 1.10-rc still on beta1

**Comment by pierrre** [comment]
https://github.com/docker-library/golang/blob/master/README.md

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/golang" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/golang), especially [PRs with the "library/golang" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fgolang). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3904
