### ISSUE TITLE
Document where GOROOT is

### ISSUE THREAD

**Issue by kevinburke** [docker-library/golang#206]
I need to set GOROOT explicitly in the environment to use a third party tool. What is the GOROOT I should use? It would be nice if this was documented.

**Comment by tianon** [comment]
Here's a generic method which can be used for _any_ reasonable Go environment to determine the appropriate value:

```console
$ docker run --rm golang:1.9 go env GOROOT
/usr/local/go
```

So, you could write a `Dockerfile` line something like this:

```dockerfile
RUN set -eux; \
	export GOROOT="$(go env GOROOT)"; \
	./run-tool-which-requires-GOROOT-set.sh
```

**Comment by kevinburkeomg** [comment]
Thanks - I guess what I am hoping for is that you include this in the public documentation available at https://hub.docker.com/_/golang/.

I just searched for the answer to this question again and landed on this (closed) ticket.
