### ISSUE TITLE
latest tagged arch-specific images are multi-arch manifest lists instead of single image manifest

### ISSUE THREAD

**Issue by deitch** [docker-library/golang#214]
The manifest for the multi-arch images are correctly multi-arch manifest lists. Thus, running `docker pull golang` on any supported arch works correctly, pulling the image for that arch.

However, if I try to pull a specific arch image using the `latest` tag, it fails. This is because the manifest on those images is a multi-arch manifest list with a single entry, rather than a single manifest. For the actual tagged versions, the manifests are single manifests, and work correctly.

To replicate, try doing the following on an `amd64` machine:

* `docker pull golang` - works, pulls an `amd64` image
* `docker pull arm64v8/golang:1.10.0-alpine` - works, pulls the `arm64v8` image
* `docker pull arm64v8/golang` (implicit or explicit `latest`) - FAILS

The failure is shown below:

```
$ docker pull arm64v8/golang
Using default tag: latest
latest: Pulling from arm64v8/golang
no matching manifest for linux/amd64 in the manifest list entries
```

The reason is because the manifest for `arm64v8/golang:latest` is a multi-arch manifest list with a single entry, instead of a single manifest, as the `arm64v8/golang:1.10.0-alpine` is.

Manifest for `arm64v8/golang:1.10.0-alpine` - correct single manifest:

```
$ manifest-tool inspect arm64v8/golang:1.10.0-alpine
arm64v8/golang:1.10.0-alpine: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:4ee08d87cb2d22c505ad83635b62e63804d986e8e31361efae03cd1bdfca36a7
Architecture: arm64
          OS: linux
    # Layers: 6
      layer 1: digest = sha256:b78042c299ad99d1e646b18762d4bc22a84c4f88e5bb491ea6293a10f53ddf79
      layer 2: digest = sha256:6fd45b97b6c2a3ac869ae5c99e087e97bc29714b165180e06f0c9116f400f2dd
      layer 3: digest = sha256:660093e5ae1b303373dac44a518743db0a535330a44f561a0b1c66c666b88102
      layer 4: digest = sha256:8569aa5fa4d278f38f6cc0343e9466d5f72fe50fdf3b7b718188bbb79cfd85d9
      layer 5: digest = sha256:4aa9d41ce1fa8f979262115f154b87d701f1ec2a2ded5f91c8cc4b7c43e40f7c
      layer 6: digest = sha256:54ce6514b3ea0064acae9bacab64946f16e64276b4378cc6bd2d28ac9f61ed54
Raw
```

Manifest for `arm64v8/golang:latest` - manifest list:

```
$ manifest-tool inspect arm64v8/golang
Name:   arm64v8/golang (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:a00018f9ce2dce9a348f5967dcb86b9e10658a9935b90cd1befee1a33d61e53c
 * Contains 1 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:fe4c1aa86d7b7a4c4244b7f2f4e56f43af50fdf746139ec89732630b0c70bc96
1  Mfst Length: 1796
1     Platform:
1           -      OS: linux
1           - OS Vers:
1           - OS Feat: []
1           -    Arch: arm64
1           - Variant: v8
1           - Feature:
1     # Layers: 7
         layer 1: digest = sha256:3476b6ec1aa77d47beaf22adc259097130bcc9eec853636fb1dcf4f5c2925a56
         layer 2: digest = sha256:eab7dbcb22e5d9d968cd5d78dfb96bf92704a665b3d1710483048568abd1ba5b
         layer 3: digest = sha256:03e8835ddfb1ea03693a4eb69d729fa15c982207e1518c3dd84f76336f920f9d
         layer 4: digest = sha256:bade4a02b1a0af4c7b52bcd066c9d44034d712a06638e6e7dbb69c1127476aa9
         layer 5: digest = sha256:8b5d347d8b1cf0e5e44efc946e168812b756706e1ae04089babac994e94c5a53
         layer 6: digest = sha256:0add559507ed05f8a9a9e30cd8868a6ef7d9d19295cb35fd44929f5d16281463
         layer 7: digest = sha256:3e934158b556f80c9548884ce26221ec1fb66448357f30b451b0f37ea203e042
```

**Comment by yosifkit** [comment]
Yes, this is known and is an artifact of how images and manifests are created and pushed.  See [here](https://github.com/docker-library/oi-janky-groovy/blob/455ed054fdc20e0f0914eaf71a6e1b74d2910988/multiarch/vars.groovy#L75-L187) for the code that pushes to the individual architectures (like `arm64v8`) and [here](https://github.com/docker-library/oi-janky-groovy/tree/455ed054fdc20e0f0914eaf71a6e1b74d2910988/put-shared) for the code that does the pushing of manifests to the empty (aka `library`) namespace.

From my perspective the single architecture manifest on `arm64v8/golang:latest` is more correct than `arm64v8/golang:1.10.0-alpine` and that `docker` should allow a power user to specify the arch they want to pull. See also upstream issues of https://github.com/moby/moby/issues/36552 and https://github.com/moby/moby/issues/35158.

**Comment by deitch** [comment]
> From my perspective the single architecture manifest on arm64v8/golang:latest is more correct than arm64v8/golang:1.10.0-alpine

Why? Isn't the current canonical way to pull an image for another arch to use the label of the underlying single manifest (vs manifest list) image that is referenced in the manifest list?

> docker should allow a power user to specify the arch they want to pull.. See also upstream issues ...

Agreed. But it doesn't right now, so anyone who wants to pull, e.g. `golang` for `arm64v8` while working on `amd64` expects to be able to do `pull arm64v8/golang:latest`. That is what you do for `alpine`, `openjdk`, etc. etc.

Of course, once the upstream issues are fixed, the "best" (subjectively speaking) way will be to pull referencing the manifest list and giving the arch (although I can see some issues with that), `docker pull --arch=arm64v8 golang:latest` or similar, but until then, why hurt the dev experience unnecessarily?

**Comment by tianon** [comment]
What @yosifkit is saying is that this is a quirk of how `:latest` and friends work within the official images program at large -- they're what we call "shared tags", and technically could include _multiple_ images within that same tag, which is why they're implemented via manifest list.

The links @yosifkit has provided are just _some_ of the places that would need to be changed in some way to special case these to be direct image pushes instead.

**Comment by deitch** [comment]
Hi @tianon . Thanks for the explanation.

> that this is a quirk of how :latest and friends work within the official images program at large -- they're what we call "shared tags", and technically could include multiple images within that same tag, which is why they're implemented via manifest list.

Hmm. There is nothing special about `latest` per se; it is just a convention that it is mutable. Are you saying that the way that images are construct for the `library/<repo>` repos has its own standards for `latest` that insist on it being a manifest list? Even when it is not just in `library/<repo>` but also `<arch>/<repo>`?

**Comment by tianon** [comment]
Yes, see https://github.com/docker-library/official-images/blob/8140c49974e31cfec512aab9aff83fcf602a93ed/library/golang#L27 and https://github.com/docker-library/official-images/blob/8140c49974e31cfec512aab9aff83fcf602a93ed/library/golang#L9.

**Comment by deitch** [comment]
Does that affect `<arch>/golang:latest` in addition to just `library/golang:latest`? Why should it?

**Comment by tianon** [comment]
That file is the single source of truth for ALL builds of the "golang"
official image, regardless of which architecture or namespace they are
built for or pushed to.

**Comment by deitch** [comment]
Putting `latest` in `SharedTags` means that it will create a `library/golang:latest` with a multi-arch manifest. Got that. But it **also** means that it will create `arm64v8/golang:latest` as a multi-arch manifest with just one arch's manifest in it? Seems silly to me, but I didn't write it. I would have put `SharedTags` _only_ against `library/<image>` and put all `Tags` on `<arch>/<image>`. But I didn't write it. :-)
