### ISSUE TITLE
Golang 1.10.1 Images not reachable

### ISSUE THREAD

**Issue by XenoPhex** [docker-library/golang#216]
Despite the [Official Docker Hub GoLang Page](https://hub.docker.com/r/library/golang/) listing GoLang 1.10.1 images, I get the following error message:
```
$ sudo docker run golang:1.10.1-stretch go version
Unable to find image 'golang:1.10.1-stretch' locally
docker: Error response from daemon: manifest for golang:1.10.1-stretch not found.
See 'docker run --help'.
```
If we try that again with the `latest` version:
```
$ sudo docker run golang:stretch go version
... # Trimming download output
go version go1.10 linux/amd64
```
I'm also noticing that the `1.10.1` tags do not exist on DockerHub. Any chance someone missed updating DockerHub with the new images?

**Comment by yosifkit** [comment]
Build is still in progress. This one is currently pushing to the `amd64/` namespace: https://doi-janky.infosiftr.net/job/multiarch/view/flat/job/amd64/job/golang/.  And then [put-shared](https://doi-janky.infosiftr.net/job/put-shared/job/light/) needs to run to push manifest lists the the empty (`library/`) namespace.

**Comment by ElfoLiNk** [comment]
@yosifkit https://doi-janky.infosiftr.net/job/put-shared/job/light/ seems failing so 1.10.1 is not getting pushed

**Comment by yosifkit** [comment]
Amd64 images should be good now.  Other architectures are currently building.
