### ISSUE TITLE
Images for Go 1.10.2

### ISSUE THREAD

**Issue by goenning** [docker-library/golang#220]
It seems like a bot updated the Dockerfiles to 1.10.2 [329b6672949337c4469351b2e8b8575459a75c7f], but it didn't get published to the docker registry.

I tried to use `generate-stackbrew-library.sh` to generate the files and send a PR to `docker-library/official-images`, but I can't get it to work. Is anyone planning to send the PR? If not, is there any guide on how to do it? Thanks!

**Comment by praseodym** [comment]
I just submitted a PR: https://github.com/docker-library/official-images/pull/4317
