### ISSUE TITLE
World-writeable /go/bin/

### ISSUE THREAD

**Issue by jsha** [docker-library/golang#223]
This Docker image creates a /go/bin/ directory with world-writeable permissions. This became an issue when I tried to use `fpm` to package a Go binary. `fpm` rightly complains when there is a world-writable directory in the PATH.

```
$ docker run golang:1.10.2 ls -ld /go/bin
drwxrwxrwx 2 root root 4096 May  5 05:52 /go/bin
```

Proposed solution: Ensure /go/bin/ is created with 0755 permissions.

Thanks for listening!

**Comment by tianon** [comment]
See #44 for the PR which made this change and #43 for the issue where it was initially proposed and discussed for some of the rationale behind the current setting.
