### ISSUE TITLE
time lib not working as expected in container

### ISSUE THREAD

**Issue by deltaskelta** [docker-library/golang#226]
Hi. I may have missed something, but on my local system, everything behaves as expected, but in the container, something seems off

main.go
```
package main

import (
	"fmt"
	"time"
)

func main() {
	t, err := time.Parse(time.RFC1123, "Fri, 22 Jun 2018 13:00:00 KST")
	if err != nil {
		panic(err)
	}

	fmt.Println(t.String())
	fmt.Println(t.UTC().String())
	fmt.Println(t.UTC().Equal(t))
}
```

Dockerfile
```
FROM golang:latest

COPY main.go /go/src/test/main.go
WORKDIR /go/src/test

CMD go run main.go
```

On my local system, the output from this program is:

```
2018-06-22 13:00:00 +0900 KST
2018-06-22 04:00:00 +0000 UTC
true
```

but if I build and run it in a container I get this:

```
2018-06-22 13:00:00 +0000 KST
2018-06-22 13:00:00 +0000 UTC
true
```

which seems to be converting the timezone to UTC, but it is not changing they time so they are not equal

**Comment by deltaskelta** [comment]
hmm ok. If the loading of the location seems to work, then how could that be done programmatically? I can't guarantee that the incoming time will always be KST. Would moving to an offset based scheme like RFC1123Z be the best route?

**Comment by yosifkit** [comment]
I'm not sure which format would be best for your needs, but it looks like this is a known limitation of `time.Parse`:

> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use ParseInLocation.
>
> https://godoc.org/time#Parse
