### ISSUE TITLE
cgo runtime error with golang:1.11beta2-alpine3.7

### ISSUE THREAD

**Issue by mfridman** [docker-library/golang#230]
Trying to run a few tests inside this container and seeing cgo errors:

```sh
GOGC=off go test -run ...

# runtime/cgo
exec: "gcc": executable file not found in $PATH
```

Is this by design, where the consumer of the image must `apk add gcc` and fix any dependency issues, `apk add musl-dev` ?

EDIT: the docker image already has those items

https://github.com/docker-library/golang/blob/9d80ad8bdf0abe15bdd3fbc77f92b17e69fe9284/1.11-rc/alpine3.7/Dockerfile#L16-L23

Noticed a similar issue here, golang/go/issues/26307

**Comment by tianon** [comment]
If you look a little further down, the Alpine image removes those again:

https://github.com/docker-library/golang/blob/9d80ad8bdf0abe15bdd3fbc77f92b17e69fe9284/1.11-rc/alpine3.7/Dockerfile#L55

See also https://hub.docker.com/_/golang/, under "`golang:alpine`":

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

And https://github.com/docker-library/golang/issues/119.
