### ISSUE TITLE
Go Binaries compiled without Stack Protection

### ISSUE THREAD

**Issue by brompwnie** [docker-library/golang#231]
Good day,
It appears that Go binaries compiled on the docker container are built without Stack Protection

**Comment by yosifkit** [comment]
If you are talking about the binaries for go itself (like `go` and `gofmt`), then you would have to convince [go upstream](https://golang.org/) since we don't compile them: 

https://github.com/docker-library/golang/blob/5d648be144af4fb0ffa29cc7f21d84c610901703/1.10/stretch/Dockerfile#L29-L30

**Comment by brompwnie** [comment]
@yosifkit apologies for not being clear enough. I am referring to Go code being compiled on the containers. I.e 
```
FROM golang:1.10
ADD main.go /app/
WORKDIR /app
RUN go build -o aBinary
```

And if you inspect the binary "aBinary" with "hardening-check" (Available on Ubuntu):
```
$-> hardening-check aBinary
aBinary:
Position Independent Executable: no, normal executable!
 Stack protected: no, not found!
 Fortify Source functions: no, only unprotected functions found!
 Read-only relocations: yes
 Immediate binding: no, not found!
```
you will see that it has been compiled without stack protection.

**Comment by yosifkit** [comment]
As far as I can tell, that is how all go code is compiled: https://github.com/golang/go/issues/21871.

**Comment by brompwnie** [comment]
That appears to be the case however it seems that "go build" is relying on the underlying gcc/clang implementation as stack protection is enabled on Ubuntu(gcc) but not on OSX(clang).

**Comment by tianon** [comment]
Since there doesn't seem to be anything we can really do here, I'm going to close.  If we can get a recommendation from upstream on whether we should do anything to resolve this, we'd be happy to update the image to do so. :+1:

**Comment by toonsevrin** [comment]
I managed to enable stack protection through:
```bash
export CGO_LDFLAGS='-fstack-protector'
```

**Comment by huornlmj** [comment]
`go build -ldflags "-s -w" -buildmode=pie main.go` works but only yields a properly hardened binary on Ubuntu systems.  Go build on CentOS for some reason miss many protections and don't make it into the binary.  Check for yourself with checksec on the same code compiled with my command line on a Ubuntu and a CentOS system.  Ubuntu system will be green across the board, CentOS will be missing RELRO, stack canary and no fortification.
