### ISSUE TITLE
go 1.11 release

### ISSUE THREAD

**Issue by bacongobbler** [docker-library/golang#233]
https://blog.golang.org/go1.11

**Comment by tao12345666333** [comment]
See PR #234

**Comment by ebati** [comment]
Is it necessary to open issue/PR in github.com/docker-library/official-images as well? also 1.10.4 is merged but not in https://hub.docker.com/_/golang/

**Comment by tao12345666333** [comment]
@ebati   Yes, after the PR be merged.

> See a change merged here that doesn't show up on Docker Hub yet?
Check the "library/golang" manifest file in the docker-library/official-images repo, especially PRs with the "library/golang" label on that repo.

> For more information about the official images process, see the docker-library/official-images readme.

**Comment by fterrag** [comment]
@tao12345666333 Thanks for managing this. Any idea on when the 1.11 tag will be made available on Docker Hub? It looks like the PR (https://github.com/docker-library/golang/pull/234) was merged a couple of hours ago.

Thanks again!

**Comment by tao12345666333** [comment]
@fterrag  Pending on https://github.com/docker-library/official-images/pull/4779 . The tag 1.11 will be available after it be merged.

**Comment by fterrag** [comment]
@tao12345666333 makes sense. Thanks
