### ISSUE TITLE
Getting this error fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by rajkotraja** [docker-library/golang#237]
cd ../.. &&   docker run   --rm   -v $(pwd):/go/src/github.com/Psiphon-Labs/psiphon-tunnel-core   psiandroid   /bin/bash -c 'cd /go/src/github.com/Psiphon-Labs/psiphon-tunnel-core/MobileLibrary/Android && ./make.bash' ; cd -
+ '[' '!' -f make.bash ']'
+ PRIVATE_PLUGINS_TAG=
+ BUILD_TAGS='OPENSSL '
+ GOOS=arm
+ go get -d -v -tags 'OPENSSL ' github.com/Psiphon-Labs/psiphon-tunnel-core/MobileLibrary/psi
github.com/Psiphon-Inc/bolt (download)
github.com/Psiphon-Inc/crypto (download)
github.com/Psiphon-Inc/dns (download)
github.com/Psiphon-Inc/goarista (download)
github.com/Psiphon-Inc/goptlib (download)
github.com/Psiphon-Inc/goregen (download)
# cd .; git clone https://github.com/Psiphon-Inc/goregen /go/src/github.com/Psiphon-Inc/goregen
Cloning into '/go/src/github.com/Psiphon-Inc/goregen'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/Psiphon-Inc/goregen: exit status 128
github.com/Psiphon-Inc/goselect (download)
# cd .; git clone https://github.com/Psiphon-Inc/goselect /go/src/github.com/Psiphon-Inc/goselect
Cloning into '/go/src/github.com/Psiphon-Inc/goselect'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/Psiphon-Inc/goselect: exit status 128
github.com/Psiphon-Inc/openssl (download)
# cd .; git clone https://github.com/Psiphon-Inc/openssl /go/src/github.com/Psiphon-Inc/openssl
Cloning into '/go/src/github.com/Psiphon-Inc/openssl'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/Psiphon-Inc/openssl: exit status 128
github.com/Psiphon-Inc/ratelimit (download)
# cd .; git clone https://github.com/Psiphon-Inc/ratelimit /go/src/github.com/Psiphon-Inc/ratelimit
Cloning into '/go/src/github.com/Psiphon-Inc/ratelimit'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/Psiphon-Inc/ratelimit: exit status 128
github.com/Psiphon-Inc/sss (download)
# cd .; git clone https://github.com/Psiphon-Inc/sss /go/src/github.com/Psiphon-Inc/sss
Cloning into '/go/src/github.com/Psiphon-Inc/sss'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/Psiphon-Inc/sss: exit status 128
Fetching https://golang.org/x/net/proxy?go-get=1
Parsing meta tags from https://golang.org/x/net/proxy?go-get=1 (status code 200)
get "golang.org/x/net/proxy": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/proxy?go-get=1
get "golang.org/x/net/proxy": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
/root/psiphon-tunnel-core-master/MobileLibrary/Android

**Comment by wglambert** [comment]
>docker run --rm -v $(pwd):/go/src/github.com/Psiphon-Labs/psiphon-tunnel-core psiandroid

We don't maintain this image https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/master/MobileLibrary/Android
