### ISSUE TITLE
Go 1.11 modules require git

### ISSUE THREAD

**Issue by fluxynet** [docker-library/golang#238]
Hello,
When building go 1.11 applications, git is required for dependency management using go mod.
Should git not be added? e.g. in alpine images via `apk add git` ?

**Comment by yosifkit** [comment]
Short answer: nope.

Long answer: It is left out on purpose. From the [docs](https://github.com/docker-library/docs/tree/4f5a2136aa69f916ee7f63fea647e06bde19c23f/golang#golangversion-alpine) that appear on Docker Hub:

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).
