### ISSUE TITLE
Errors in the "Start a Go instance in your app" section ?

### ISSUE THREAD

**Issue by pmcgrath** [docker-library/golang#24]
From reading the [Image Dockerfile]( https://github.com/docker-library/golang/blob/4d4b14164e50c089a09b9364697749dc7f764824/1.3/onbuild/Dockerfile) I needed to make the following changes to get the "Start a Go instance in your app" to work, if anyone has the same problem I can create a pull request

Dockerfile ?
===
Should CMD not be 
CMD ["app"] 
rather than CMD ["./myapp"]

- If the Dockerfile is in the same directory then the executable will be "app" based on the content being copied to the /go/src/app directory
- Also relies on /go/bin being on the path and since go install is called via the wrapper, hence no local executable in the WORKDIR

Build step ?
===
docker build -t my-golang-app
Missing a trailing " ." to build for current directory

**Comment by yosifkit** [comment]
This all seems fixed in the latest docs.
