### ISSUE TITLE
GOROOT is not set in docker image

### ISSUE THREAD

**Issue by xue35** [docker-library/golang#240]
Hello

I notice that envrionment variable GOROOT is not set in golang docker image which actually lead to some down-stream project error. 

And in Dockerfile, golang is installed into ‘usr/local/go’ with hard code, which is not nicely programmed.

Cheers,

**Comment by wglambert** [comment]
https://github.com/docker-library/golang/issues/206#issuecomment-360592675
```console
$ docker run --rm golang:1.9 go env GOROOT
/usr/local/go
```

**Comment by tianon** [comment]
Duplicate of #206.
