### ISSUE TITLE
linux/arm64 not in the manifest

### ISSUE THREAD

**Issue by haydenhughes** [docker-library/golang#242]
When trying to pull any variant of `library/golang:1.11` on an arm64 system it errors with `no matching manifest for linux/arm64 in the manifest list entries`. Pulling `arm64v8/golang:1.11` works. Just a stab in the dark but maybe it could be caused by the latest [arm64v8 build failing](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/golang/)?

**Comment by tianon** [comment]
I think this one was actually a case of https://github.com/docker-library/official-images/issues/3835 -- it's fixed now. :+1:
