### ISSUE TITLE
sys logging does not work out of the box

### ISSUE THREAD

**Issue by luisgarciaalanis** [docker-library/golang#252]
BUG: images are missing rsyslog service preventing applications from using the Linux system level logger.

The following app returns: Unix syslog delivery error
```
package main

import (
	"fmt"
	"log"
	"log/syslog"
)

func main() {
	logwriter, err := syslog.New(syslog.LOG_NOTICE, "myprog")
	if err != nil {
		fmt.Println(err.Error())
	}
	log.SetOutput(logwriter)
}
```

Should the images be including this basic system feature?

**Comment by tianon** [comment]
This "basic system feature" is actually a daemon just like any other (it just happens to commonly place its Unix socket under `/dev` instead of `/run`), so installing the package for it wouldn't actually do anything.  If you need syslog, I'd recommend running it in a separate container and using TCP or a Unix socket in a shared volume to write to it.

**Comment by luisgarciaalanis** [comment]
I tried apt-get installing rsyslog and it does fix the issue, I just wondered if it was worth including this functionality on the base containers. If not I will create a custom image and publish it.

**Comment by tianon** [comment]
It might fix the issue temporarily by creating a dummy `/dev/log` in that one container, but it doesn't actually fix the issue in the sense that `/dev/log` will exist in a new container nor will it make `/dev/log` magically log anywhere.  On your host, `/dev/log` (the standard syslog socket) is just a standard Unix socket (which happens to commonly live under `/dev` for legacy reasons) to a daemon running on the host.  In order for "syslog" to work the way you expect it to inside a container, you need that same `/dev/log` Unix socket provided by _something_ (either a bind-mount to the host so it can communicate directly to the host's syslog server or using something like `s6` or `supervisord` to run a separate `syslog` server inside your container alongside your application).
