### ISSUE TITLE
request: multiarch debian stretch-based versions  for arm32v5

### ISSUE THREAD

**Issue by rmoriz** [docker-library/golang#263]
Hi,

docker-ce for Raspbian should again support older Raspberry Pi devices (arm32v5) as it did up until 18.06 (see moby/moby#38175). While I try to debug that issue, I couldn't find a debian stretch based golang image for arm32v5 anymore, using the available alpine-based images leads to dependencies to musl-libc:

```
cd /go/src/github.com/docker/cli && \
	LDFLAGS='' DISABLE_WARN_OUTSIDE_CONTAINER=1 make VERSION=0.0.0-20190204010345-8a8ad78fb1 GITCOMMIT=8a8ad78fb1 dynbinary manpages
make[2]: Entering directory '/go/src/github.com/docker/cli'
./scripts/build/dynbinary
/lib/ld-musl-armhf.so.1: No such file or directory 
Makefile:63: recipe for target 'dynbinary' failed
```

**Comment by tianon** [comment]
The Go project does not release official binaries for ARMv5, which is why we don't have a build there.

As for the Alpine (`arm32v6`) variants, you probably need to install `gcc` and/or `libc-dev` (and likely other things, if the goal is to build Docker from source).

**Comment by rmoriz** [comment]
After digging deeper into docker-ce packaging (see moby/moby#38175)  it looks to me like the arm32v7 was used and `GOARM` was set to "6" to cross-compile (well, sort of) the docker binaries to run on arm32v6. 

Sorry for the invalid issue.
