### ISSUE TITLE
Cross-builds for ARM not working

### ISSUE THREAD

**Issue by StefanScherer** [docker-library/golang#267]
When I want to cross-build an ARM image on a amd64 machine (Docker Desktop on Mac, or eg. CircleCI with QEMU registered) I have a problem when the base image is only available with a manifest list.

For example the arm32v7/golang image is provided with a manifest list only. On Docker Desktop I get this error:

```
$ docker pull arm32v7/golang
Using default tag: latest
latest: Pulling from arm32v7/golang
no matching manifest for unknown in the manifest list entries
```

The arm32v7/node image can be used without a problem

```
$ docker pull arm32v7/node
Using default tag: latest
latest: Pulling from arm32v7/node
...
```

Any ideas of the manifest list experts how I can use the ARM golang image for cross-building?

**Comment by tianon** [comment]
Tags like `latest`, `1`, `1.12`, `1.12.0` are what we call "shared tags" (meaning they're shared between Windows and Linux via manifest list).  If you want the image directly (sans the manifest list), you need to use one of the "Simple" tags (https://github.com/docker-library/official-images/blob/30610a00789ddf37e26c698e8b2ce5e82e908f46/library/golang#L8-L9) like `1.12-stretch`. :+1:

**Comment by StefanScherer** [comment]
Thanks @tianon, I tried to inspect a few tags, but it seems I stopped before 1.12-stretch 😅. Thanks, that's good to know. 👍
