### ISSUE TITLE
build Mellanox go project 'docker-sriov-plugin' error

### ISSUE THREAD

**Issue by Whishay** [docker-library/golang#270]
Hi,
I am trying to compile a project listed below on both cenots 7.4 and fedora 27 but failed at very beginning with the following error messaages. The original go versions were 1 .11.3+ on both OSes and I tried to downgrade them to 1.10.1 according to the error messages and the help from the project but it made no sense. I am not sure if it is an issue here. any clue? thanks a lot.
Project:  https://github.com/Mellanox/docker-sriov-plugin

Version and error messages:
#go version
go version go1.10.1 linux/amd64
#docker images
REPOSITORY TAG IMAGE ID CREATED SIZE
docker.io/rdma/sriov-plugin latest 54e32a483991 9 months ago 63.4 MB
docker.io/rdma/sriov-plugin x86_64 54e32a483991 9 months ago 63.4 MB
docker.io/golang 1.10.1 1af690c44028 11 months ago 780 MB
#./build make
Building image: rdma/sriov-plugin:x86_64
Sending build context to Docker daemon 213.5 kB
Step 1/13 : FROM golang:1.10.1 as build
Error parsing reference: "golang:1.10.1 as build" is not a valid repository/tag: invalid reference format

**Comment by tianon** [comment]
That error looks like your Docker version is too old.

**Comment by tao12345666333** [comment]
Multi-stage builds are a new feature requiring Docker 17.05 or higher on the daemon and client.
