### ISSUE TITLE
Latest image for s390x

### ISSUE THREAD

**Issue by barthy1** [docker-library/golang#271]
I'm using the golang for s390x and I tried to pull the latest image but I've got an error:
```
# docker pull golang
Using default tag: latest
latest: Pulling from library/golang
no matching manifest for unknown in the manifest list entries
```
The same result is for `golang:1.12.3`, `golang:1.12`
However I can pull `s390x/golang` image
```
# docker pull s390x/golang
Using default tag: latest
latest: Pulling from s390x/golang
Digest: sha256:29f452b3dbca1a99b7d4ecfe51320bfe11242a3d2e27b2f7231a7da80df3161d
Status: Image is up to date for s390x/golang:latest
```
`./manifest-tool-linux-s390x inspect golang | grep s390x` returns nothing

Is there no s390x support anymore for multiarch `golang:x` images?

**Comment by tianon** [comment]
Looks like a case of
https://github.com/docker-library/official-images/issues/3835

(If you check again now, the manifest list entry should be there.)

**Comment by barthy1** [comment]
Thank you, it works now.
