### ISSUE TITLE
golang:1.12.4 does not have layers for linux/arm*

### ISSUE THREAD

**Issue by seemethere** [docker-library/golang#274]
It's been 4 days since https://github.com/docker-library/golang/commit/8f2f8502c173fbbcf33fcde5566ca53ad1070ae8 was merged and the armv6, armv7, and armv8 images haven't been published to hub yet.

As confirmed with:
```
❯ docker manifest inspect golang:1.12.4 | jq '.manifests | .[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "386",
  "os": "linux"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.14393.2906"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17134.706"
}
{
  "architecture": "amd64",
  "os": "windows",
  "os.version": "10.0.17763.437"
}
```

**Comment by wglambert** [comment]
https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/golang/206/console
`error: file write error (No space left on device)`

Woops

**Comment by tianon** [comment]
Good catch -- working on getting that one under control (it's building now, hopefully available soon).

Looking into what's up with arm32, since they both built successfully so should've been included in the manifest list already.

**Comment by tianon** [comment]
Much better:
```console
$ manifest-tool inspect golang:1.12.4 | grep arm
2           -    Arch: arm
3           -    Arch: arm64
```

:+1:

**Comment by seemethere** [comment]
Thanks @tianon!
