### ISSUE TITLE
Issues with pipes in compiled golang

### ISSUE THREAD

**Issue by Aidamina** [docker-library/golang#276]
I can't wrap my head around why I am unable to use pipes in an app compiled with the docker golang container.

Created an example use case here, where I created a cat clone to demonstrate the issue.

[https://github.com/Aidamina/golang-docker-pipe-issues
](https://github.com/Aidamina/golang-docker-pipe-issues
)

In short if I pipe:
echo "test" |  ./app
The compiled golang app wont be able to detect the stdin input during runtime.

I hope I am missing something obvious.

**Comment by wglambert** [comment]
Does your app process `stdin` outside of a Docker environment?

**Comment by Aidamina** [comment]
@wglambert to quote from my repository:

This does work

echo "test" | go run main.go
This does work

go build -o golang-docker-pipe-issues .
echo "test" | ./golang-docker-pipe-issues
This does not work

echo "test" | docker run --rm -i  $(docker build -q .)
This does not work

docker run --rm -i $(docker build -q .) echo "test" | ./golang-docker-pipe-issues

**Comment by Aidamina** [comment]
It appears the issue was related to the way the OS presents the stdin to the process.

On my development box (MacOS) the call to:
```
os.Stdin.Stat()
```
Is populated differently than in a linux environment.
Size information seems to not be available during runtime.
