### ISSUE TITLE
Missing nanoserver dockerfiles

### ISSUE THREAD

**Issue by dcormier** [docker-library/golang#277]
In ddb228343a2433319f0b7e2dc6a2b884447f732c the EOL'ed `golang:nanoserver-sac2016` was removed, but, unfortunately, I'm not seeing the tags for `golang:nanoserver-1803` and `-1809` (which would be based on [the still-supported versions of nanoserver](https://hub.docker.com/_/microsoft-windows-nanoserver)).

It seems like `golang:nanoserver-sac2016` was the last published tag based on nanoserver. It would be helpful to get `golang:nanoserver-1803` or at least `-1809` published.

**Comment by wglambert** [comment]
See https://github.com/docker-library/openjdk/issues/295#issuecomment-486407726
>The `nanoserver:sac2016` tag is the only one we were ever based on (the last tag that still contained Powershell and thus was possible for us to build a useful image off of)

**Comment by dcormier** [comment]
However, according to [this](https://docs.microsoft.com/en-us/windows-server/get-started/nano-in-semi-annual-channel), there are still official images with powershell on nanoserver. They just moved [here](https://hub.docker.com/r/microsoft/powershell/).

**Comment by tianon** [comment]
Those images are not one of the allowable exceptions for official images base images (only the stock Windows Server Core and Nano Server images are, and those only because Windows literally cannot be supported without them).
