### ISSUE TITLE
Not reachable to new images on docker-hub

### ISSUE THREAD

**Issue by michilu** [docker-library/golang#279]
* [golang - Docker Hub](https://hub.docker.com/_/golang?tab=description)

It seems like no yet start to build new images. ex) 1.12.5 and 1.10.10

It is known that the docker-hub had the security alert at last April and ask some users re-connect to repositories.
Are you have been any impacted?

**Comment by yosifkit** [comment]
Update done via https://github.com/docker-library/official-images/pull/5867 (and amd64 images are pushed with other architectures following shortly)
