### ISSUE TITLE
In Windows images, env var 'GOPATH' points to empty folder.

### ISSUE THREAD

**Issue by olegburov** [docker-library/golang#288]
It seems like all Windows images has the same issue. The environment variable `GOPATH` points to the path `C:\gopath`, but there is nothing inside this directory.

https://github.com/docker-library/golang/blob/ce2392f637d95ca2a09dee58d04578948c520cca/1.12/windows/windowsservercore-1803/Dockerfile#L40-L41

The reason because Golang is installed into the path `C:\go`.

https://github.com/docker-library/golang/blob/ce2392f637d95ca2a09dee58d04578948c520cca/1.12/windows/windowsservercore-1803/Dockerfile#L51-L71

Shouldn't `GOPATH` points to `C:\go`?

**Comment by tianon** [comment]
`GOPATH` is where _your_ source code belongs (unless you're using Go Modules).

I believe you're thinking of `GOROOT` (which is supposed to point to the Go installation and we don't set it because Go itself detects the correct value appropriately).

**Comment by tianon** [comment]
See https://github.com/golang/go/wiki/GOPATH for additional useful details on this.

**Comment by olegburov** [comment]
@tianon, right I mixed `GOROOT` with `GOPATH`, but it's still a bit confusing that

- on Linux:

  * the environment variable `GOROOT` points to `/usr/local/go`
  * the environment variable `GOPATH` points to `/Users/<user-name-here>/go`

- on Windows:

  * the environment variable `GOROOT` points to `C:\Go`
  * the environment variable `GOPATH` points to `C:\Users\<user-name-here>\go`

- in Linux container:

  * the environment variable `GOROOT` points to `/usr/local/go`
  * the environment variable `GOPATH` points to `/go`

- in Windows container:

  * the environment variable `GOROOT` points to `C:\go`
  * the environment variable `GOPATH` points to `C:\gopath`

I think the root issue comes from the Go Team when they decided to install the source for Go projects and their binaries (`GOROOT`) into the root of system drive (`C:\`). It's not where I would expect it to get installed on Windows. The right place would be `C:\Program Files\Go` (`GOROOT`). Then inside Windows container it would looks like:

* the environment variable `GOROOT` points to `C:\go`
* the environment variable `GOPATH` points to `C:\Program Files\Go`

As an example, Microsoft installs [.NET Core](https://dotnet.microsoft.com/download) (OSS) using the following locations:

- in Linux container `/usr/share/dotnet`, see [here ](https://github.com/dotnet/dotnet-docker/blob/master/3.0/sdk/alpine3.9/amd64/Dockerfile) for details. 
- in Windows container `C:\Program Files\dotnet`, see [here](https://github.com/dotnet/dotnet-docker/blob/master/3.0/sdk/nanoserver-1903/amd64/Dockerfile) for details.

**Comment by tianon** [comment]
So, I get that this is confusing, but what I'm not getting is what harm this causes?  The `GOPATH` environment variable is set appropriately (usable both for things like `$GOPATH/src/...` and `go get` to pick up automatically), and `GOROOT` is not set at all (the `go` tool figures out the appropriate value automatically).  If the exact value of these are needed, that's what `go env XXX` is for (and for many users running Go on their host, the values of these will vary wildly depending on their personal preferences, how they obtained Go, etc so any scripts needing these variables would have to tolerate them being very different).

**Comment by wglambert** [comment]
Going to close since this seems resolved

**Comment by tianon** [comment]
As a bit of a necro-update, I've filed https://github.com/docker-library/golang/pull/377 to change this in Go 1.17+ (now that it's changed in Go's installers and we have an upstream version to toggle on for a minor backwards compat break).
