### ISSUE TITLE
Go 1.11+ projects require git (alpine-based image)

### ISSUE THREAD

**Issue by PhilippHeuer** [docker-library/golang#297]
In reference to the issue #238 which was closed with the following quote:

> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar).

Go 1.11+ projects that use go modules are not usable as go directly invokes the git binary which is not present in the container. Go modules are the most official way for projects right now and every project using this can not be build in the `golang:alpine` image.

I think the git dependency is a hard requirement, not optional/additional and would be happy if we can discuss adding it to the official image.

**Comment by tianon** [comment]
If you use `-mod=vendor`, `git` is definitely not required (although that does assume the project is using `go mod vendor`, which I don't think is really all that big of a leap -- vendoring is very popular in the Go community).

**Comment by leighmcculloch** [comment]
If you're dependent on source control tools you could also be dependent on mercurial and bazaar, depending on where your dependencies are hosted. It might make sense to install git, etc in an image you base on the alpine image to keep them lightweight.

The need for source control tools dissipates with Go 1.13 as that release uses the Go proxy to download `tar` files by default.

**Comment by PhilippHeuer** [comment]
Thanks, i already migrated to 1.13 but didnt know about that feature yet, so i was still maintaining my own image with git.

Thats great news, this resolves my issue and i don't have to maintain and update my own golang alpine image anymore.
