### ISSUE TITLE
Discrepancy in glibc versions on golang stretch images.

### ISSUE THREAD

**Issue by gglachant** [docker-library/golang#298]
Hi everyone,

There is a discrepancy between the glibc version of golang images stored in the Docker Hub repository and those manually generated using the Dockerfiles in this repository (`glibc 2.28-10` vs. `2.24-11+deb9u4`).

Current stretch and buildpack-deps all have version glibc version 2.24, that I can see.

I've noted this discrepancy in golang tags `1.12.7` through `1.12.9` and `1.11.11` through `1.11.13`. Tags `1.12.6` and `1.11.10` have glibc version 2.24.

Running the current official `golang:1.12.9` image:
```
$ docker run --rm -it golang:1.12.9 ldd --version
Unable to find image 'golang:1.12.9' locally
1.12.9: Pulling from library/golang
4ae16bd47783: Pull complete 
bbab4ec87ac4: Pull complete 
2ea1f7804402: Pull complete 
96465440c208: Pull complete 
16a3d8aca6cd: Pull complete 
e0ec5610455a: Pull complete 
96d705baf026: Pull complete 
Digest: sha256:584daefca21d7b8f0702e70bfe6a31c3a6def12ed4145a8d6fe78c205f124f1e
Status: Downloaded newer image for golang:1.12.9
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Manually building the `golang:1.12.9` image from this repository
```
$ cd golang/1.12/stretch
$ docker build --pull --no-cache -t local-golang:1.12.9 .
Sending build context to Docker daemon  3.584kB
Step 1/8 : FROM buildpack-deps:stretch-scm
stretch-scm: Pulling from library/buildpack-deps
Digest: sha256:f1de17fd4fc503ef597923608f64ff2486e961f7a594e74f8c1d478bddb891e2
Status: Image is up to date for buildpack-deps:stretch-scm
 ---> 699d7e41a39e
[...]
Removing intermediate container 7f2d19739ba4
 ---> e350820b43af
Successfully built e350820b43af
Successfully tagged local-golang:1.12.9
$ docker run --rm -it local-golang:1.12.9 ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I suspect something changed within the upstream images (i.e. `buildpack-deps:stretch-scm`) since the point in time the official golang images were rebuilt.

The reason I am reporting this issue is that go program binaries currently built and linked against `glibc-2.28-10` are unable to run on official stretch images that embark `glibc 2.24-11` (i.e. `2.24-11+deb9u4` as of now), for instance those on the Google Cloud Platform.

We get the following error:
```
<path to binary>: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by <path to binary>)
```

Regards and thanks for your help.

Gabriel

**Comment by wglambert** [comment]
`golang:1.12.9` is on Buster by default, which uses 2.28.
https://github.com/docker-library/golang/pull/290

`latest` shares the tag with `buster`
https://github.com/docker-library/docs/tree/master/golang#shared-tags

We don't have a great way of notifying users of updates to the images outside of them checking the golang [pull requests](https://github.com/docker-library/golang/pulls), [commit history](https://github.com/docker-library/golang/commits/master), or official-image updates for the golang tag https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fgolang+is%3Aclosed

**Comment by gglachant** [comment]
Ah ! That completely makes sense.

So forcing the use of stretch (i.e. `golang:1.12.9-stretch`) solves our issue.

Apologies for the noise.

Thank you very much.

Gabriel
