### ISSUE TITLE
Set GOPROXY=direct by default in docker images for 1.3+

### ISSUE THREAD

**Issue by tamalsaha** [docker-library/golang#303]
Due to various privacy concerns, can you set GOPROXY=direct by default in docker images for 1.3+ ?

Thanks.

**Comment by yosifkit** [comment]
We aren't going to change the default provided in Go releases (https://proxy.golang.org).  See their privacy page https://proxy.golang.org/privacy and evaluate whether this is acceptable for your use case (as with any hosted service).

There a quite a few others providing a similar service and self-hosted options too: https://github.com/golang/go/wiki/Modules#are-there-always-on-module-repositories-and-enterprise-proxies
