### ISSUE TITLE
Include Debian Slim image

### ISSUE THREAD

**Issue by jaztec** [docker-library/golang#305]
I like the small size of the Alpine image but within some project I really miss full blown features (like `/dev/log` for instance).

In my opinion a Debian Slim image could really by a useful midway between Alpine and full Debian, it would not diminish the right of existence for an Alpine image (can think of loads of uses there) however it would add uses for programs that are just a bit to intensive for the bare-bones Alpine installments but also don't justify a complete Debian installment either (scaling). I've looked up the base templates for the Debian setup and reiterated the request there as well: https://github.com/docker-library/buildpack-deps/issues/99

Please consider adding a Debian like Slim package to the available Golang images. And of course, I do not mind contributing

**Comment by tianon** [comment]
I'm not sure I understand what `/dev/log` has to do with Alpine, or any Docker image for that matter?  `/dev/log` is typically a unix socket created by some user-mode application (like `syslog-ng`, `systemd-journald`, etc), not a feature of the distribution. :confused:

I think the general consensus for usage of this repo is that it typically wouldn't be your runtime base and you'd use it more for building your project and then copying the resulting binary into a separate image that's `FROM debian:xxx-slim`, for example.  (Using Docker's multi-stage builds make this especially easy to accomplish.)

**Comment by hazcod** [comment]
How about replacing the debian image with the slim variant?

**Comment by jaztec** [comment]
Excuse me, it was a misunderstanding from my side. I'll close the issue

**Comment by anarcat** [comment]
> I think the general consensus for usage of this repo is that it typically wouldn't be your runtime base and you'd use it more for building your project and then copying the resulting binary into a separate image that's `FROM debian:xxx-slim`, for example. (Using Docker's multi-stage builds make this especially easy to accomplish.)

I still feel it would be worth using debian's slim images for this. What exactly do we need from the main debian image here that couldn't be accomplished with the slim images?

**Comment by tianon** [comment]
There's nothing that couldn't be accomplished with the slim images, but rather that we'd then have to duplicate the list of installed SCMs from `buildpack-deps:bullseye-scm` (which is what we're currently `FROM`).

(See also #427 where this is being actively discussed again.)
