### ISSUE TITLE
Add Go 1.13.2

### ISSUE THREAD

**Issue by kevinburkemeter** [docker-library/golang#307]
Go 1.13.2 was just released with a security fix. It would be good to update the official images to point to it.

**Comment by mikeatlas-r7** [comment]
Yep, also looking for `1.12.11` for the same reason.

**Comment by leighmcculloch** [comment]
Also Go 1.13.13 and 1.12.12 were released shortly after.

**Comment by tao12345666333** [comment]
Open a PR for update to golang 1.13.3 and 1.12.12 https://github.com/docker-library/official-images/pull/6805

It seems that we need to add 1.13.2 and 1.12.11 later. @tianon  Bot skipped them.

**Comment by tianon** [comment]
> It seems that we need to add 1.13.2 and 1.12.11 later. @tianon Bot skipped them.

Is there a compelling reason to backfill these?  I get why upstream released the security fix standalone separately (easier for downstreams to cherry-pick, justify, etc), but I don't really see a reason for us to explicitly backfill them in given that the later releases include the security fixes too and folks are likely to simply update to the latest in 1.13 or 1.12 series.

**Comment by leighmcculloch** [comment]
> Is there a compelling reason to backfill these?

Consistency. It would be odd if there was a specific version of Go missing from an otherwise reasonably complete set of versions.

Also Go's security and non-security patches are often released close together like this. In theory a user can adopt only the security fixes which may be less risky than adopting a larger set of fixes, or at least defer the larger set of fixes until they've had time to review them more thoroughly.

**Comment by mikeatlas-r7** [comment]
From our perspective, whatever is the latest available that includes the latest security patches is what we will take up as soon as possible.

**Comment by tao12345666333** [comment]
>Is there a compelling reason to backfill these?

Personally, I will update to the latest version as soon as possible to facilitate the maintainability of my software.  So even if there is no 1.13.2, it will be fine for me.

But considering the official image as a “basic software”, it is true that the above situation (like @leighmcculloch ‘s comments) may exist for the average user.

**Comment by mikeatlas-r7** [comment]
`1.12.12` is good enough for our needs - thanks everyone.

**Comment by tianon** [comment]
> Also Go's security and non-security patches are often released close together like this. In theory a user can adopt only the security fixes which may be less risky than adopting a larger set of fixes, or at least defer the larger set of fixes until they've had time to review them more thoroughly. In this case if someone wanted to adopt only the security fixes they'd be pulling 1.13.2/1.12.11 so it'd be good to support them.

They're usually done closely, but I think this is the first time they're back-to-back like this, right?  (Maybe I'm misremembering.)

Either way, this has happened via #309. :+1:
