### ISSUE TITLE
Server IP can't be reached after restarting container

### ISSUE THREAD

**Issue by nikolasborrel** [docker-library/golang#31]
I have created a GCE instance as described at https://blog.golang.org/docker. Because I'm using a private repository, I have to manually run the container (sudo docker run my/image) works fine and the http server IP can be reached.

Two containers seems to run, though I would have expected only one running:

~$ sudo docker ps
CONTAINER ID   IMAGE             COMMAND                PORTS      NAMES
c71dedc0b6de   my/image:latest   "/bin/sh -c /Users/n   8080/tcp   cocky_wright                                              
959df573ccb0   my/image:latest   "/bin/sh -c /Users/n                     k8s--compute_-_webservice.5ebf7573--1.http--bac9fbf1 
 
Now, stopping both containers (docker stop container_id) and re-running my container makes the server IP not reachable and only one container is running in contrary to the first time the container is run. What is the problem here?

Moreover, mounting a volume always creates only one container and hence the server can newer be reached (only a problem on the GCE instance, it works locally):

sudo docker run -v /local/mount/dir:/image/mount/dir my/image:latest --rm my/image:latest

**Comment by yosifkit** [comment]
closing old unrelated issue.
