### ISSUE TITLE
Please add support for GOPROXY build-arg

### ISSUE THREAD

**Issue by anguslees** [docker-library/golang#315]
`GOPROXY` is very much like `http_proxy` and is expected to be used/set by the build environment, not by the source project.  Please add `ARG GOPROXY` to the standard golang Dockerfiles >= 1.13, so this value may be provided externally during docker-based golang builds.

Note that there are actually several relevant environment variables, so we may as well support all of them at the same time.  I think the build-args we should add are: `GOPROXY`, `GONOPROXY`, `GOPRIVATE`, `GOSUMDB`, `GONOSUMDB`.

Note also that I'm not suggesting we change any upstream defaults, only that we provide _the ability_ to configure these values when appropriate (unlike #303, for example).

(I think this is technically a trivial/obvious edit, but let me know if it would be easier if I provided a concrete PR.)

**Comment by tianon** [comment]
I'm not sure I understand what you're asking for -- what concrete change are you suggesting we make?

As-is, I don't believe there's anything preventing you from using `-e` on `docker run`, `ENV` or `ARG` in a `Dockerfile`, etc to set these variables however you wish in your own builds/environments, nor do I see anything concrete we could add to make it "easier" or more possible than it already is. :confused:

**Comment by JulienBreux** [comment]
Hi! 👋 

You just can use `docker run -e GOPROXY=https://proxy.inodes.org <>` ?

Or:
```
FROM ...

ENV GOPROXY=https://proxy.inodes.org
```

In your Dockerfile?

**Comment by tianon** [comment]
Yep, both of those should work just fine.

**Comment by anguslees** [comment]
I want `docker build --build-arg=GOPROXY ...` to work (and the other vars mentioned above). I believe (from a quick experiment and scan of docs) that this requires `ARG GOPROXY` in the Dockerfile - you can't just make up a build-arg on the command line (like you can with env).

In particular, build-args do not get captured in the resulting layers, which is appropriate for GOPROXY, and do not affect the resulting container - they're purely a build-time parameter.

**Comment by tianon** [comment]
Right, but if that's something you want for builds of your image, the `ARG` needs to be defined in *your* `Dockerfile` -- us adding them to this repository's `Dockerfile` won't actually do anything.

**Comment by tianon** [comment]
To put that another way, if we add `ARG GOPROXY` to our `Dockerfile`, that metadata will *only* affect the following lines in the `Dockerfile` here, and will *not* be preserved as an available `ARG` in the final image which others consume.

**Comment by anguslees** [comment]
Oh you're right - build-args aren't inherited.  Sorry, I should have verified that first :/

Closing this unimplementable feature request.

**Comment by anguslees** [comment]
Aha, reopening.

Please add the following to the golang dockerfile:
```
ONBUILD ARG GOPROXY
ONBUILD ARG GONOPROXY
ONBUILD ARG GOPRIVATE
ONBUILD ARG GOSUMDB
ONBUILD ARG GONOSUMDB
```

**Comment by yosifkit** [comment]
While `ARG`  doesn't fit some of the arguments we've used in the past when dropping `ONBUILD` images (https://github.com/docker-library/official-images/issues/2076), we still rather not add any `ONBUILD` instructions to official-images.

---

I don't want to introduce unexpected "magic" that will skew users expectations for how Docker images work.  Without being able to control if and when they trigger, `ONBUILD` instructions are a mistake and should instead just be regular instructions in the user's Dockerfile.

Assuming they were added to golang, then this contrived dockerfile would have to redo the apt layer when the user has to change one of the build-args that really only affects the go build line

```
FROM golang
# ONBUILD's trigger here

RUN set -ex; \
	apt-get update; \
	apt-get install -y some-build-deps; \
	rm -rf /var/lib/apt/lists/*

COPY my-go-code /where/i/want/it/
RUN go build .......
```
