### ISSUE TITLE
Add bullseye base image

### ISSUE THREAD

**Issue by inductor** [docker-library/golang#316]
The latest Debian version 11 is named as bullseye and it is already available for the base image 

Ref: https://github.com/docker-library/buildpack-deps/blob/3c71697594e9eef1d673df9f1d379fdc0f7ff111/bullseye/scm/Dockerfile

**Comment by tianon** [comment]
Given that Bullseye is still the ["Debian Testing" distribution](https://www.debian.org/devel/testing) (and thus not security-supported, might include breakage, etc) and is not currently "frozen" we have no plans to support it yet.

Once one of the Bullseye freeze periods start (https://release.debian.org/bullseye/freeze_policy.html), we might be more willing to consider supporting it as an official variant.

That being said, building it yourself should be relatively trivial (I imagine just swapping the relevant `Dockerfile` from `buster` to `bullseye` would do the trick, assuming Debian doesn't have a major transition in progress that prevents it from building/working properly at the moment).
