### ISSUE TITLE
Add linux/s390x to golang:1.12.17

### ISSUE THREAD

**Issue by StefanScherer** [docker-library/golang#321]
I'm trying to build containerd on s390x. The CI pipeline uses `golang:1.12.17` right now. But the build fails as it doesn't find the image for this platform.

```
$ docker run --rm mplatform/mquery golang:1.12.17
Image: golang:1.12.17
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - windows/amd64:10.0.14393.3506
   - windows/amd64:10.0.17763.1040
```

I found the image at `s390x/golang:1.12.17-buster`. I saw you already cleaned up this repo for 1.14 and 1.13 only.

How hard is it to add `linux/s390x` to the manifest list in `golang:1.12.17`?
Asking for a friend ;-)

**Comment by yosifkit** [comment]
We do not have a way to fix an old tag. This only affects shared tags, so add `-buster` (`golang:1.12.17-buster`) should work just fine and no `s390x/` needed.

**Comment by tianon** [comment]
I did some testing and found it seems to be a Go tooling bug, and filed https://github.com/estesp/manifest-tool/issues/86 accordingly (with my research notes).  Phil's agreed to give us a new `manifest-tool` release, but it's the witching hour on the east coast already so he'll probably get to it next week. :+1:

**Comment by StefanScherer** [comment]
Thanks @yosifkit! Indeed, the `golang:1.12.17-buster` helps in our CI pipeline for now. 🎉 
Thanks @tianon for looking into the root cause. 👍 Phil already released a new version 💪.
Newer images `golang:1.13` and `golang:1.14` already have s390x included, so I'm looking forward to update golang as soon as possible.
Thanks for your help.
