### ISSUE TITLE
Build pipeline blocked, prevents publishing Go 1.14.2

### ISSUE THREAD

**Issue by karalabe** [docker-library/golang#322]
Go 1.14.2 was released some hours ago and it features a few important fixes. Please push the docker images when you have time. Thank you!

**Comment by karalabe** [comment]
Hmm, the repository seems to have been updated, but the build tags aren't pushed to docker hub yet. Maybe they take that much to propagate through the system?

**Comment by karalabe** [comment]
I think it might be this job that's blocking the pipeline https://doi-janky.infosiftr.net/job/put-shared/job/light/job/golang/, though I've no idea how the builders work, just seeing this as stuck.

**Comment by billinghamj** [comment]
it seems like it's gotten stuck in some way: https://doi-janky.infosiftr.net/job/put-shared/job/light/job/golang/1699/console

**Comment by billinghamj** [comment]
(for six days!!)

**Comment by tklauser** [comment]
The same sees to be true for the Go 1.13.10 docker image.

**Comment by billinghamj** [comment]
Looks like it's fixed :)

**Comment by tianon** [comment]
Yep, thanks for the heads up -- it should be fine now! :+1:
