### ISSUE TITLE
/go is world writeable in final images

### ISSUE THREAD

**Issue by tobert** [docker-library/golang#324]
At the end of the build process for these containers, there is a `chmod -R 777 $GOPATH` that makes it trivial to tamper with the go binaries. It's probably not a huge deal in practice, but probably puts a lot of folks out of compliance with security guidelines.

The offending line is here (and in the other golang Dockerfiles)
https://github.com/docker-library/golang/blob/master/1.14/alpine3.11/Dockerfile#L63

I also validated on golang:latest:
```
atobey@Amys-MBP % docker run -ti golang ls -al /go
total 16
drwxrwxrwx 4 root root 4096 Apr 23 20:05 .
drwxr-xr-x 1 root root 4096 Apr 24 20:17 ..
drwxrwxrwx 2 root root 4096 Apr 23 20:05 bin
drwxrwxrwx 2 root root 4096 Apr 23 20:05 src
```

**Comment by tobert** [comment]
Here's the PR where it's introduced and reviewed with a "LGTM" from @tianon.
https://github.com/docker-library/golang/pull/44

And apparently someone else reported this and it was closed with a pointer to PRs where it seems the implications of these filesystem permissions are proposed and accepted without much regard for the security implications:
https://github.com/docker-library/golang/issues/223

As an owner of production systems I feel like the rationale for setting world-writable bits on everything under `/go` deserves some easy to find documentation. I was surprised to find this bit of code in the Dockerfile and am also surprised the various container scanners aren't calling this out as a problem.

**Comment by yosifkit** [comment]
While the `777` directory is insecure for normal host setups, there are not other processes or users in the container so this is equivalent to `700` for normal usage but still allows flexibility for any user ID to be the "owner" by using `--user` when running the container.

It does make sense to call this out in the documentation.
