### ISSUE TITLE
Go v1.12 alpine images don't have git installed

### ISSUE THREAD

**Issue by dmlambea** [docker-library/golang#328]
Trying to build a module-enabled project with  `go build -o sample ./cmd/sample/...` fails with an error:

`go: github.com/stretchr/testify@v1.5.1: git init --bare in /go/pkg/mod/cache/vcs/ed2f58bca3966d01dc4666baa48276a4fab360938a8d941050d58e371e2bba77: exec: "git": executable file not found in $PATH
`

More recent versions of Go work flawlessly.

**Comment by wglambert** [comment]
https://github.com/docker-library/golang/issues/250#issuecomment-438486997

https://github.com/docker-library/golang/issues/250#issuecomment-451201761
>As discussed above, adding `git` to the Alpine variant can currently be accomplished with a very trivial `Dockerfile` similar to the following:

```dockerfile
FROM golang:1.11-alpine3.8
RUN apk add --no-cache git
```
