### ISSUE TITLE
golang:1-alpine image no longer has git

### ISSUE THREAD

**Issue by klmitch** [docker-library/golang#346]
It appears that an upstream change to the `alpine` container has caused `git` to no longer come pre-installed.  This has broken go within the `golang:1-alpine` image, as it uses `git` to implement `go get`, and presumably other commands.  The `Dockerfile-alpine.template` should be updated to ensure `git` is installed.

**Comment by tianon** [comment]
https://github.com/docker-library/golang/pull/347#issuecomment-717388734 :+1:

(Closing in favor of the discussion on #345)
