### ISSUE TITLE
Apps using `os/user` won't build on Nanoserver due to missing `NetApi32.dll`

### ISSUE THREAD

**Issue by micahyoung** [docker-library/golang#348]
Expected behavior:

Should build and print out "ContainerUser" on `golang:nanoserver`:
```
package main

import (
	"fmt"
	"os/user"
)

func main() {
	user, _ := user.Current()

	fmt.Printf("Name: %s\n", user.Name)
}
```

Observed:
```
panic: Failed to load netapi32.dll: The specified module could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(...)
        c:/go/src/syscall/dll_windows.go:320
syscall.(*LazyProc).Addr(...)
        c:/go/src/syscall/dll_windows.go:327
syscall.NetGetJoinInformation(0x0, 0xc0000cbcb0, 0xc0000cbcac, 0xd, 0xc0000a2260)
        c:/go/src/syscall/zsyscall_windows.go:1804 +0x107
os/user.isDomainJoined(0xc0000cbd08, 0xe7bbae, 0x0)
        c:/go/src/os/user/lookup_windows.go:18 +0x5a
os/user.lookupFullName(0xc0000a40b0, 0xc, 0xc0000a40a0, 0xd, 0xc0000a2260, 0x1a, 0xd, 0xc0000a2260, 0x1a, 0x1)
        c:/go/src/os/user/lookup_windows.go:51 +0x2d
os/user.newUser(0xc0000a4070, 0xc, 0xc0000a4090, 0xc, 0xc0000a2220, 0x16, 0xc0000a40a0, 0xd, 0xc0000a40b0, 0xc, ...)
        c:/go/src/os/user/lookup_windows.go:181 +0xd4
os/user.current(0x0, 0x0, 0x0)
        c:/go/src/os/user/lookup_windows.go:225 +0x2d8
os/user.Current.func1()
        c:/go/src/os/user/lookup.go:15 +0x29
sync.(*Once).doSlow(0xf9ffc0, 0xf07958)
        c:/go/src/sync/once.go:66 +0xf7
sync.(*Once).Do(...)
        c:/go/src/sync/once.go:57
os/user.Current(0xc0000cbf48, 0xe74ae5, 0xf8bcc0)
        c:/go/src/os/user/lookup.go:15 +0x105
main.main()
        C:/gopath/main.go:9 +0x2d
exit status 2
```

Potential fix in [template](https://github.com/docker-library/golang/blob/master/Dockerfile-windows-nanoserver.template):
```
...
COPY --from=mcr.microsoft.com/windows/servercore:1809 /Windows/System32/NetApi32.dll /Windows/System32/NetApi32.dll
...
```

**Comment by tianon** [comment]
Ah, I think this isn't a case of "won't built" but actually "won't run", right?  So this is needed for running the resulting build, not for creating the build.

While unfortunate, I'm honestly wondering why we still support Nano Server images here - I'm not sure I understand the use case for them in the toolchain images (adding them was a case of being excited that we could, and not spending much time thinking about whether we should).

**Comment by micahyoung** [comment]
Oops, yes "won't run" is correct. After some more searching, Microsoft does appear to be looking into adding `NetApi32.dll` into `nanoserver` itself so I'm happy have it done there instead: https://github.com/microsoft/Windows-Containers/issues/72

The biggest benefit for myself is that the `golang:nanoserver` images are about 200MB vs `golang:servercore` still being over 2GBs - similar argument for  `alpine` over `ubuntu` I suppose, though in the Windows case over an order of magnitude difference (meaning longer and more expensive CI runs, longer Windows VM setup time due to pulling, also Microsoft may start rate-limiting the base layers like everyone else, etc).

My typical use-case for `golang:nanoserver` is cross-compiling and testing simple Go binaries, with a repo containing a  `Dockerfile.windows` using `golang:nanoserver`  and a `Dockerfile` using `golang:alpine`, wired up to GitHub actions or other CI with Windows and Linux runners to `docker build` then copy and publish artifacts. My local setup is a Mac workstation with a Docker Desktop Linux daemon and a remote Windows daemon, which I connect to with `docker -H <windows host> build -f Dockerfile.windows` for Windows images. 

My `Dockerfile`s usually build and run some basic smoke tests since it's a nice isolated environment, which works identically in CI and locally, and I don't need to use a Windows machine directly. And `golang:nanoserver` has been sufficient for quite a while now, I just happened to be making an app with a `user.Current()` which led to this issue and the workaround. With this fixed, I suspect `nanoserver` will continue to be the best option for most of my use-cases.

**Comment by tianon** [comment]
Ah, fair enough - yeah, I'd much rather see this fixed in the upstream images (since this is kind of a hairy workaround), so I guess we'll follow https://github.com/microsoft/Windows-Containers/issues/72 and see where it goes. :eyes:
