### ISSUE TITLE
vulnerability present in golang:1.13-alpine3.12

### ISSUE THREAD

**Issue by dravos** [docker-library/golang#349]
Security fixes made in [alpine 3.12.2](https://www.alpinelinux.org/posts/Alpine-3.12.2-released.html) were included when updating golang alpine versions 1.14-alpine3.12 and 1.15-alpine3.12. However, this update has not yet been made for golang1.13-alpine3.12. 

Would it be possible to make this update?

Thanks for your time!

**Comment by tianon** [comment]
Unfortunately, Go upstream no longer supports Go 1.13, so our image's support matrix reflects that (and thus that image will not be updated).

**Comment by dravos** [comment]
I understand. Thanks for your help!
