### ISSUE TITLE
1.16-alpine Image build fails for i386 architecture because of #355

### ISSUE THREAD

**Issue by urfin78** [docker-library/golang#359]
Hello,

I'm using the alpine i386 Version of the Image as base for one of my projects.
Obviously the Jenkins build for the 1.16 version on i386 architecture fails  because of #355

https://doi-janky.infosiftr.net/job/multiarch/job/i386/job/golang/360/

> export GO386="softfloat"'
> + eval 'export GOARCH="386"
> export GOOS="linux"
> export GO386="softfloat"'
> + export 'GOARCH=386'
> + export 'GOOS=linux'
> + export 'GO386=softfloat'
> + '[' -n linux ]
> + '[' -n 386 ]
> + cd /usr/local/go/src
> + ./make.bash
> Building Go cmd/dist using /usr/lib/go. (go1.15.7 linux/386)
> go tool compile: exit status 1
> unsupported setting GO386=softfloat

The new option or the GO386 setting is not supported by the go version used in the build process.
I don't know if it's fixable on the the Jenkins side or if the option has to be removed to build the new image. Can somebody take a look at this?

Thanks
Thomas

**Comment by yosifkit** [comment]
:cry: https://git.alpinelinux.org/aports/commit/?id=b8cdcf4ed68be1c263713465e6469496349497b4

So it seems we need 1.16 tn order to build 1.16 without `SSE2` support... thanks go. https://github.com/golang/go/issues/44500 
 (and soon https://github.com/golang/go/issues/44505).
