### ISSUE TITLE
Proposal: Set second GOPATH to vendor dependencies in on-build images

### ISSUE THREAD

**Issue by discordianfish** [docker-library/golang#36]
Hi,

to me, mostly influenced by http://peter.bourgon.org/go-in-production/, the nicest way to vendor dependencies is by just adding a second GOPATH pointing to your/import-path/_vendor.

Since the ON-BUILD steps happen *before* you can set any env variables in your Dockerfile, you can't use this pattern right now.

Therefor I suggest to set a second GOPATH pointing to _vendor like this. I assume that should work by simply setting GOPATH to "/go:/go/src/app/_vendor". This way people can just add the deps they want to _vendor and they're done.

**Comment by yosifkit** [comment]
Closing old issue, if you feel this was closed in error please let us know.
