### ISSUE TITLE
1.16.3 images with digests modified

### ISSUE THREAD

**Issue by aanm** [docker-library/golang#363]
It seems that ~10h ago some tags were updated. As there does not seem to be a PR that could explain why an image tag was modified, I wonder if this is was done by accident.

The image digest for 1.16.3 was previously: `docker.io/library/golang@sha256:13457efbeae175217436dbbdb9ba621bd42934a1cddcce2b8b60b99db4e11d12`

it seems now it is: `docker.io/library/golang@sha256:7f69ee6e3ea6c3acab98576d8d51bf2e72ed722a0bd4e4363423fddb3958d5af`

Both digests still exist in DockerHub but only the `7f..` is the one with the `1.16.3` tag (the above digests are for the manifest list, the following digests are for a linux/amd64 machine):
```
$ uname -op
x86_64 GNU/Linux
$ docker images
REPOSITORY                        TAG                                        IMAGE ID       CREATED         SIZE
golang                            1.16.3                                     cbf5edf38f6b   3 days ago      862MB
golang                            <none>                                     0debfc3e0c9e   12 days ago     862MB
```

cc @tianon

**Comment by yosifkit** [comment]
We have a repo that tracks all image changes along with their digests, and other information. If you look at the history of [`golang/remote/1.16.3`](https://github.com/docker-library/repo-info/commits/master/repos/golang/remote/1.16.3.md), you can see that Windows images were rebuilt following a patch Tuesday which causes the manifest list to be updated:

https://github.com/docker-library/repo-info/commit/29669521e4f82ea81ac0e5e4c81fab65ff773ec0#diff-fc78a2fa05922f2ceabf07fabd31f30dc2f8812917a6985ee0ecc133d9a7299fL17-R18

**Comment by yosifkit** [comment]
For an general overview of the build process: https://github.com/docker-library/faq/#an-images-source-changed-in-git-now-what

Also note: 
> We strive to publish updated images at least monthly for Debian and Ubuntu. [...] These refreshed base images also means that any other image in the Official Images program that is FROM them will also be rebuilt
>
> \- https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by aanm** [comment]
Oh great, thanks for the clarification! I didn't know about the history of [golang/remote/1.16.3](https://github.com/docker-library/repo-info/commits/master/repos/golang/remote/1.16.3.md). Thank you!
