### ISSUE TITLE
https://github.com/docker-library/golang/blob/master/1.16/alpine3.13/Dockerfile line 113 should change chmod privs

### ISSUE THREAD

**Issue by eric-w-hart** [docker-library/golang#366]
Line 113 is using chmod 777 perms. I feel this isn't a good security practice and a better method would be to use 755.

**Comment by tianon** [comment]
See https://github.com/docker-library/golang/issues/324#issuecomment-642328520 and https://github.com/docker-library/docs/pull/1750/files
