### ISSUE TITLE
Alpine 3.14 images have no architecture available

### ISSUE THREAD

**Issue by DasSkelett** [docker-library/golang#374]
Hey, looks like #373 didn't fully work out. While the tags for these Alpine 3.14 images are showing up in Docker Hub, there are no images available for any architecture.

![image](https://gitlab.com/DasSkelett/NetKAN-Status-Exporter/uploads/ae275be587b61ce8e76dd2d92edf1959/image.png)
(applies to all 3.14 tags)

https://hub.docker.com/_/golang?tab=tags&page=1&ordering=last_updated

Pulling fails with this error:
```
$ doc pull golang:alpine3.14
alpine3.14: Pulling from library/golang
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by yosifkit** [comment]
Thanks for the heads up. We are aware that many of our Alpine 3.14 based builds are failing. :disappointed: :bowing_man: 

Related: https://github.com/docker-library/official-images/pull/10379#issuecomment-863396878

**Comment by tianon** [comment]
Builders are updated and builds are either queued or in progress -- sorry for the delay!
