### ISSUE TITLE
os.Stderr doesn't write to stderr under docker compose?

### ISSUE THREAD

**Issue by dmolesUC** [docker-library/golang#376]
I have a fairly basic Go web app that logs to stderr via `log.Printf()`. When I run it natively, or in Docker using `docker build / docker run`, I get the log output to stderr. When I run it with `docker-compose`, however, I can only get the log output with `docker compose logs` -- it doesn't appear on the console.

Things I've tried:

1. Replacing `log.Printf()` with `os.Stderr.WriteString()`, in case it was specific to `log`:
   - same result -- output appears in compose logs, but not on console
2. Replacing my executable in the `ENTRYPOINT` with a simple shell script (`while true; do >&2 date; sleep 1; done`)
   - shell script output _does_ appear both in the console and in compose logs

### Steps to reproduce:

1. clone the repository [github.com/dmoles/adler](https://github.com/dmoles/adler).

   ```sh
   git clone git@github.com:dmoles/adler.git
   ```

2. in the new clone, check out the tag [docker-compose-logs](https://github.com/dmoles/adler/tree/docker-compose-logs).

   ```sh
   cd adler
   git checkout docker-compose-logs
   ```

3. build and run the compose stack.

   ```sh
   docker compose up
   ```

### Expected

- After `Attaching to adler_1`, console shows something like:

  ```none
   adler_1  | 2021/07/09 20:18:01 Serving from /go/src/app on port 8181
   ```

### Actual

- Console shows nothing after `Attaching to adler_1`
- `docker compose logs adler` shows the expected line

**Comment by tianon** [comment]
My best guess is a race between `start` and `attach` in `docker-compose`; I can't reproduce using https://gist.github.com/tianon/8af1ab065844fe0ed01d126cd8637687 (which is roughly the same thing but hyper minimized):

```console
$ docker-compose --version
docker-compose version 1.26.2, build eefe0d31

$ docker-compose build --pull
Building foo
Sending build context to Docker daemon  36.86kB

Step 1/5 : FROM golang:1.15-buster
1.15-buster: Pulling from library/golang
Digest: sha256:be0a1cbaa012e1e2f182beab451205db1f1573b9b72afdfff786e7bf8fce7818
Status: Image is up to date for golang:1.15-buster
 ---> 53b7b7a65524
Step 2/5 : WORKDIR /go/src/foo
 ---> Using cache
 ---> 52b21fbf4f65
Step 3/5 : COPY . .
 ---> c961dc210da3
Step 4/5 : RUN go install -v ./...
 ---> Running in 0a70aab2f4ec
foo
Removing intermediate container 0a70aab2f4ec
 ---> 7849974cc8a3
Step 5/5 : CMD ["foo"]
 ---> Running in b8ef7c687d5f
Removing intermediate container b8ef7c687d5f
 ---> 339c1b9e3311
Successfully built 339c1b9e3311
Successfully tagged tmp_foo:latest

$ docker-compose up
Creating network "tmp_default" with the default driver
Creating tmp_foo_1 ... done
Attaching to tmp_foo_1
foo_1  | foo
tmp_foo_1 exited with code 0
```

**Comment by dmolesUC** [comment]
@tianon Interesting. Were you able to reproduce it with my repo? It occurs to me it could be somehow specific to Docker Desktop for macOS.

**Comment by wglambert** [comment]
Yeah I'd try asking over at https://github.com/docker/for-mac/issues since we're not able to reproduce outside of that
