### ISSUE TITLE
make no longer working as expected with Alpine 3.14 based containers

### ISSUE THREAD

**Issue by jufemaiz** [docker-library/golang#378]
See the following gist:

https://gist.github.com/jufemaiz/a5512eb7f87a0f33f512b806dec49e5a

`make` commands lack permissions or path or something?

**Comment by jufemaiz** [comment]
Related: https://github.com/docker-library/php/issues/1177

**Comment by tianon** [comment]
Yep, as noted in https://github.com/docker-library/php/issues/1177, this is something related to the containerization combined with newer musl.  If you're not on the latest release of Docker, libseccomp, and runc, I'd suggest starting with an update to all of those.

**Comment by jufemaiz** [comment]
Solution:

Docker 20.10.5 does not work and is the source of the problem. 

Docker 20.10.6 and 20.10.7 both work.

Why the heck that is is absolutely bizarre!
