### ISSUE TITLE
docker pull couchbaseLGTM -- is today OK too, or would you rather we wait until tomorrow or Wednesday?

### ISSUE THREAD

**Issue by yaya8754** [docker-library/golang#379]
LGTM -- is today OK too, or would you rather we wait until tomorrow or Wednesday?

Build test of #10602; c06e9c0ba; `amd64` (`couchbase:6.6.2`, `couchbase:community-6.6.0`):

```console

$ bashbrew build couchbase:6.6.2
Building bashbrew/cache:2941960186b581cc37d5aed6b12d1502488960c40db244a69b6e87c504d27406 (couchbase:6.6.2)
Tagging couchbase:6.6.2
Tagging couchbase:enterprise-6.6.2

$ test/run.sh couchbase:6.6.2
testing couchbase:6.6.2
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3]...passed
	'override-cmd' [3/3]...passed

```

```console

$ bashbrew build couchbase:community-6.6.0
Building bashbrew/cache:ae5241e36a6080354d95266446420337aa02aff5a61e2d0b14e1d8697f6b0469 (couchbase:community-6.6.0)
Tagging couchbase:community-6.6.0

$ test/run.sh couchbase:community-6.6.0
testing couchbase:community-6.6.0
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3]...passed
	'override-cmd' [3/3]...passed

```

_Originally posted by @tianon in https://github.com/docker-library/official-images/issues/10602#issuecomment-886868086_

**Comment by yaya8754** [comment]
> LGTM -- is today OK too, or would you rather we wait until tomorrow or Wednesday?
> 
> Build test of #10602; c06e9c0ba; `amd64` (`couchbase:6.6.2`, `couchbase:community-6.6.0`):
> 
> ```
> $ bashbrew build couchbase:6.6.2
> Building bashbrew/cache:2941960186b581cc37d5aed6b12d1502488960c40db244a69b6e87c504d27406 (couchbase:6.6.2)
> Tagging couchbase:6.6.2
> Tagging couchbase:enterprise-6.6.2
> 
> $ test/run.sh couchbase:6.6.2
> testing couchbase:6.6.2
> 	'utc' [1/3]...passed
> 	'no-hard-coded-passwords' [2/3]...passed
> 	'override-cmd' [3/3]...passed
> ```
> 
> ```
> $ bashbrew build couchbase:community-6.6.0
> Building bashbrew/cache:ae5241e36a6080354d95266446420337aa02aff5a61e2d0b14e1d8697f6b0469 (couchbase:community-6.6.0)
> Tagging couchbase:community-6.6.0
> 
> $ test/run.sh couchbase:community-6.6.0
> testing couchbase:community-6.6.0
> 	'utc' [1/3]...passed
> 	'no-hard-coded-passwords' [2/3]...passed
> 	'override-cmd' [3/3]...passed
> ```
> 
> _Originally posted by @tianon in [docker-library/official-images#10602 (comment)](https://github.com/docker-library/official-images/pull/10602#issuecomment-886868086)_

**Comment by yaya8754** [comment]
Api40

**Comment by yosifkit** [comment]
Since these are copies of a comment by tianon, this looks like spam or incorrect API testing. Please run API tests on your own repos.
