### ISSUE TITLE
Alpine based golang docker image for linux/s390x architecture missing

### ISSUE THREAD

**Issue by Ashmita152** [docker-library/golang#383]
For alpine 3.14 as base image: golang image for linux/s390x arch is missing (which is available for alpine 3.13)

<img width="1607" alt="Screenshot 2021-08-19 at 9 47 24 PM" src="https://user-images.githubusercontent.com/16268376/130197906-f3a44775-0c95-4538-a474-5151eb58ee17.png">

At first I thought it maybe due to alpine not publishing image for linux/s390x but they do publish it.

<img width="1600" alt="Screenshot 2021-08-19 at 9 48 10 PM" src="https://user-images.githubusercontent.com/16268376/130197956-8ac9638a-5de9-49a9-afbf-38001201c13d.png">

Thanks!

**Comment by yosifkit** [comment]
https://github.com/docker-library/golang/blob/0760c2984b26c28c089e41066a804ae700630d9f/1.16/alpine3.14/Dockerfile#L75-L80

```console
+ cd /usr/local/go/src
+ go env GOROOT
+ export 'GOROOT_BOOTSTRAP=/usr/lib/go' 'GOHOSTOS=linux' 'GOHOSTARCH=s390x'
+ ./make.bash
ERROR: Cannot find /usr/lib/go/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
```

I would guess it has the same root cause as https://github.com/docker-library/php/issues/1178

**Comment by tianon** [comment]
Confirmed same root cause, and confirmed same root fix :tada:

**Comment by Ashmita152** [comment]
Will 1.17-alpine3.14 tag's linux/s390x image be pushed separately or do we need to wait till next golang release ?

**Comment by yosifkit** [comment]
> Will 1.17-alpine3.14 tag's linux/s390x image be pushed separately or do we need to wait till next golang release ?

Coming soon.  They've already been pushed up to the architecture specific repo (https://hub.docker.com/r/s390x/golang), so another job will eventually combine it into the manifest list for https://hub.docker.com/_/golang.

**Comment by tianon** [comment]
It'll be pushed separately -- there's a minor delay to try and decrease
load on Docker Hub / give other arches a chance to finish building so we
can push multiple at once, but it should be up within the next hour or so.

**Comment by Ashmita152** [comment]
Thank you so much for the quick fix, much appreciated.
