### ISSUE TITLE
[Feauter] Oracle Linux 7/8 support

### ISSUE THREAD

**Issue by denismakogon** [docker-library/golang#387]
Golang on Oracle Linux deserves to exist.
Pros:
- opens a whole world of various flavors of RHEL, Fedora
Cons:
- I'm surprised that no one brought this via issue.

So, what would be nice to have:
- OEL/RHEL 7 and 8
- amd64, arm64 builds

Existing challenges: OEL 7 uses `yum`, OEL 8 uses `microdnf`. The same applies to RHEL/Fedora.

**Comment by yosifkit** [comment]
Basically the same response as https://github.com/docker-library/golang/pull/160#issuecomment-298066350 or https://github.com/docker-library/php/pull/379#issuecomment-282450199. And I'd say this doubly applies for the golang image since it doesn't have to be the runtime environment and you can `COPY` the statically compiled binary to any desired OS image.

**Comment by tianon** [comment]
Here's a simple example to illustrate:

```dockerfile
FROM oraclelinux:8-slim
ENV PATH /usr/local/go/bin:$PATH
COPY --from=golang:1.17 /usr/local/go /usr/local/go/
RUN go version
```

```console
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM oraclelinux:8-slim
8-slim: Pulling from library/oraclelinux
Digest: sha256:6a1721169ccb64a2a8977112143dd127a7e3a9665fda8774dc2459dd286f87fc
Status: Image is up to date for oraclelinux:8-slim
 ---> 70b244a7aca1
Step 2/4 : ENV PATH /usr/local/go/bin:$PATH
 ---> Running in cc1075ca4452
Removing intermediate container cc1075ca4452
 ---> 9d152600240e
Step 3/4 : COPY --from=golang:1.17 /usr/local/go /usr/local/go/
1.17: Pulling from library/golang
Digest: sha256:4f86bdd4a3118f93a4b84346458d2b88c6e8326ccc81b01d8274daf93fc0b09f
Status: Image is up to date for golang:1.17
 ---> 55fd322d995c
Step 4/4 : RUN go version
 ---> Running in 4a6622f3f41a
go version go1.17 linux/amd64
Removing intermediate container 4a6622f3f41a
 ---> a4c6df3c226a
Successfully built a4c6df3c226a
```
