### ISSUE TITLE
Add `[Net.SecurityProtocolType]::Tls12` to Go download in Windows Dockerfiles

### ISSUE THREAD

**Issue by dagood** [docker-library/golang#388]
For the Windows Dockerfiles, TLS1.2 is enabled for the Git download, but not for the Go download:

https://github.com/docker-library/golang/blob/922fb336596f79b7cd1481f154a16a4d8ab21abf/Dockerfile-windows-servercore.template#L15-L17

https://github.com/docker-library/golang/blob/922fb336596f79b7cd1481f154a16a4d8ab21abf/Dockerfile-windows-servercore.template#L66-L68

This builds fine because the download site doesn't enforce >= TLS 1.2, but I was trying to build the golang images with my own copy of Go hosted in an Azure blob storage account that does enforce it. Adding the `Tls12` line to the Go download made my custom build work.

Would it be ok to add `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;` to the Go download step in this repo?

It would help me avoid diffs in my custom build, but also maybe help in the future if Google's server starts enforcing >= TLS 1.2. (Not that I have any reason to think this will happen, to be clear. 😄)

**Comment by tianon** [comment]
Yeah, seems sane -- I wish Microsoft would fix this in the base images. :disappointed:

**Comment by dagood** [comment]
I'm new to Windows containers, but a little surprised not to see anything filed about that in https://github.com/microsoft/Windows-Containers. (Although search picks up a few issues that contain this line in a Dockerfile, one yours. 😄) Would certainly be nice. If I had a dollar for every time I've seen this line in a PowerShell script....

I'll submit a quick PR to add this line.
