### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by raffa89** [docker-library/golang#390]
Hello,
from yesterday I'm facing the error '_x509: certificate signed by unknown authority_' when downloading go dependencies/libraries.
Here is an easy way to reproduce the issue:
`docker run --rm -ti golang sh`
`go mod download golang.org/x/mod@v0.2.0`  (as in the example [here](https://golang.org/ref/mod#go-mod-download) )

**Comment by wglambert** [comment]
I'm not able to reproduce
```console
$ docker run --rm -ti golang bash
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
955615a668ce: Pull complete 
2756ef5f69a5: Pull complete 
911ea9f2bd51: Pull complete 
27b0a22ee906: Pull complete 
4e94c8ba5874: Pull complete 
103d08d8b59d: Pull complete 
a9ad1da797ad: Pull complete 
Digest: sha256:7dbfeb9d51c049e8bfe36cf1a4217c7b1ba304bf0eb72d57d0c04f405589f122
Status: Downloaded newer image for golang:latest
root@42b0f541f0f1:/go# go mod download golang.org/x/mod@v0.2.0
```

If you're using the Alpine variant then you'd want to install `ca-certificates`
