### ISSUE TITLE
Propose a Centos Based docker image

### ISSUE THREAD

**Issue by henri9813** [docker-library/golang#392]
Could you propose a centos based docker image ?

It could be helpful to test some types of scripts on CentOS directly thanks to a golang:1.17-centos docker image for example

What version of Go are you using (go version)?
every version

What operating system and processor architecture are you using (go env)?
I use Centos :-)

**Comment by yosifkit** [comment]
Duplicate of #160; response is unchanged: https://github.com/docker-library/golang/issues/387#issuecomment-908741129
