### ISSUE TITLE
Alias for supported versions

### ISSUE THREAD

**Issue by CAFxX** [docker-library/golang#394]
In line with the [upstream supported versions policy](https://golang.org/doc/devel/release#policy), I would like to suggest adding a tag (that could e.g. be called `prev` or `previous`, but I'm open to other names as well) that would always identify the second-most recent minor release. This would complement the `latest` tag to allow CI pipelines to always test the two currently-supported go releases.

To give a concrete example, as of the day of writing the most recent go release (and the one identified by `latest`) is `1.17.1`, and the proposed `prev` tag would identify go `1.16.8`. 

- When 1.17.2 is released, `prev` would still identify `1.16.8`
- When 1.16.9 is released, `prev` would identify `1.16.9`
- When 1.18 is released, `latest` would identify `1.18` and `prev` would identify `1.17.x` (where `x` would be the current 1.17 patch version at the time 1.18 comes out).

---

Outside of the scope of this issue, this could potentially be extended in the future with the `next` tag (to identify RCs) and `tip` (for the head of the go master branch), again for the sake of being able to have CI pipelines run against the most recent go RC or head, respectively.

**Comment by tianon** [comment]
I think my biggest hesitation with supporting aliases like this is that we're making up our own new terms for these releases that are a (further) delta from what upstream calls them / supports.  I can't find anywhere that "latest-1" is officially given a name beyond https://golang.org/dl/ calling both 1.17 and 1.16 "Stable versions". :confused:

**Comment by tianon** [comment]
Sorry for the delay!  Unfortunately, I don't have the bandwidth (or frankly the interest) in petitioning upstream to come up with a canonical name for "latest-1" -- however, if someone else were to successfully do so, we would gladly use it. :+1:
