### ISSUE TITLE
`i386/golang:1.17.3-*` and `i386/golang:1.16.10-*`  images missing

### ISSUE THREAD

**Issue by atc0005** [docker-library/golang#398]
I was looking for the `i386/golang:1.17.3-alpine3.14` image in particular, but it looks like all 1.17.3 and 1.16.10 images are missing from https://hub.docker.com/r/i386/golang.

Please let me know if you need more information.

Thanks.

**Comment by atc0005** [comment]
Ah, this looks to be a known issue and is likely a WIP: https://github.com/docker-library/official-images/pull/11236#issuecomment-961363269

**Comment by yosifkit** [comment]
Thanks for the issue. The trigger job for `i386` was stuck in our Jenkins instance (https://doi-janky.infosiftr.net/). The golang images should be available once the i386 builder has a chance to work through the backlog.

**Comment by atc0005** [comment]
@yosifkit Thanks!

I can confirm that these images are now available:

- `i386/golang:1.17.3-alpine3.14`
- `i386/golang:1.16.10-alpine3.14`
- `golang:1.17.3-alpine3.14`
- `golang:1.16.10-alpine3.14`
