### ISSUE TITLE
Alpine 1.15 Support

### ISSUE THREAD

**Issue by AttilaTheFun** [docker-library/golang#401]
Hello! I was wondering if/when you intend to offer a golang alpine 3.15 image. Alpine 3.15 was released on 11/24:
https://alpinelinux.org/posts/Alpine-3.15.0-released.html
Even if the 'alpine' tag doesn't get upgraded yet, having a '1.17.3-alpine-3.15' image would be greatly appreciated.
Currently I'm using one I created myself by copying the contents of your Alpine 3.14 Dockerfile and changing it to use 3.15 instead, but I'm not sure if this is the right approach.

**Comment by pnelson** [comment]
PR #400 was created for this a few days ago.

**Comment by AttilaTheFun** [comment]
Awesome @pnelson 
What has to happen in order for that to land?

**Comment by tianon** [comment]
Thanksgiving weekend to be over :wink:

**Comment by yosifkit** [comment]
https://github.com/docker-library/golang/tree/0ece21e090fa79875d2694b1d7dd4a890a5c1528#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
