### ISSUE TITLE
`Segmentation fault` when building golang plugin code in alpine arm64 image

### ISSUE THREAD

**Issue by llhuii** [docker-library/golang#402]
I have an **arm64** Ubuntu 18.04.3 LTS os, `4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:10 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`.
Run this script:
```
docker run -it golang:1.16-alpine3.14 sh -c '
apk add build-base binutils-gold
mkdir /plugin 
cd /plugin
cat > greeter.go <<'EOF'
package main

import (
        "fmt"
        _ "plugin"
)

func main() {
        fmt.Println("Hello, world")
}
EOF

go mod init plugin-demo
echo run plugin demo=====; echo
go run greeter.go
'
```

In the command `go run greeter.go`, it only reports `signal: segmentation fault (core dumped)`

**Comment by llhuii** [comment]
look like ld-musl has a problem in handling `/usr/local/go/pkg/linux_arm64/plugin.a`

**Comment by tianon** [comment]
Does this also happen with the Debian variant, or is it only the Alpine variant?  (Go doesn't officially support Alpine or musl.)

**Comment by llhuii** [comment]
> Does this also happen with the Debian variant, or is it only the Alpine variant? (Go doesn't officially support Alpine or musl.)

Only the Alpine variant. No problem in ubuntu 18.04 and the image `golang:1.16`

**Comment by llhuii** [comment]
In `golang:1.16-alpine3.14`:
1. `go run -buildmode=pie greeter.go` is OK
2. `go run -ldflags "-linkmode external -extldflags '-static'" greeter.go` is OK

**Comment by llhuii** [comment]
More: no problem in `amd64` even using `golang:1.16-alpine3.14`

**Comment by llhuii** [comment]
I manually copy `$GOROOT/src/plugin/*.go` into current directory(`/plugin`), and comment `doInit` `lastmoduleinit`.

No `segment fault` reports.

**Comment by llhuii** [comment]
It is probably `gold.ld`'s bug.

greeter.go is run as **expected** when I switch  `/usr/local/go/pkg/tool/linux_arm64/link` to use `bfd` instead of `gold.ld` by appending `-extldflags "-fuse-ld=bfd"` following https://github.com/golang/go/issues/28334#issuecomment-435666414:

Copy the output of 
```
go build -x -v -work greeter.go 2>&1| awk 'NR==1{print}$1~"go/pkg/tool/.*/link$"{$1=$1" -extldflags \"-fuse-ld=bfd\""; a=$0}END{print a}'
``` 
into shell, and run it:
```
WORK=/tmp/go-build1418567139
/usr/local/go/pkg/tool/linux_arm64/link -extldflags "-fuse-ld=bfd" -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=SNA_R-BxHM5hR4hrsjjs/dWt-EYH53VqJjVuAY3KB/f4SyhMkWYi-5ZApgvN0d/SNA_R-BxHM5hR4hrsjjs -extld=gcc /root/.cache/go-build/2f/2fa04dea12af30f252e6f54f2661b28303efa95ac8089c8a0ab1f1aa11fb0193-d

$WORK/b001/exe/a.out  ## => output as expected
```

**Comment by llhuii** [comment]
More:
If I modify [golang plugin](https://github.com/golang/go/blob/ecf6b52b7f4ba6e8c98f25adf9e83773fe908829/src/plugin/plugin_dlopen.go#L10), comment its cgo code and stub `open`/`lookup`, and compile golang from [source](https://go.dev/doc/install/source), 
Then **no segfault**.

**Comment by llhuii** [comment]
gold linker in `alpine` image can't handle gcc `no-pie` option:
```sh
docker run -it alpine sh -c '
apk add build-base binutils-gold
cat > hello.c <<EOF
#include <stdio.h>
int main() {
        printf("hello\n");
        return 0;
}
EOF

gcc -fuse-ld=gold -no-pie hello.c && ./a.out
'
```
`a.out` reports `Segmentation fault (core dumped)`.

**Comment by llhuii** [comment]
I have created an issue on alpinelinux repo: https://gitlab.alpinelinux.org/alpine/aports/-/issues/13308

**Comment by tianon** [comment]
Unfortunately, this is an issue with Go itself and its official support (really, the lack thereof) of Alpine Linux.  This is not something we plan to fix in the Docker images.
