### ISSUE TITLE
Why go install std?

### ISSUE THREAD

**Issue by rittneje** [docker-library/golang#407]
The Dockerfile currently runs `go install std`, because "the official binary release tarballs do".
https://github.com/docker-library/golang/blob/e773873197db6195f2273ba57802884d83a60d3b/1.17/alpine3.15/Dockerfile#L91-L92

What exactly is the point of this? The make.bash script will already compile the standard library packages.

It could be useful to precompile with `-race`, but this is unconditionally skipped right now.
https://github.com/docker-library/golang/blob/e773873197db6195f2273ba57802884d83a60d3b/1.17/alpine3.15/Dockerfile#L93-L94

**Comment by rittneje** [comment]
Those might just be "last updated timestamp" changes. From what I can tell `docker diff` doesn't distinguish metadata changes from content changes.

**Comment by tianon** [comment]
Doh, you're correct - I used `tar --create --directory /usr/local/go/pkg --numeric-owner --sort name --mtime=@0 .` to create a reproducible tarball of the before/after and they're 100% identical!  I guess we can safely skip that bit. :smile:

**Comment by rittneje** [comment]
> I'm hesitant because it should be reasonably easy (and fast) for users to compile for themselves but isn't needed by most use cases for the image


One thing I did want to mention on this point (re: `go install -race`) is that since it is a docker image, every time you start a fresh container, it would have to recompile the race-detected stdlib. This is different from the experience with a native toolchain, where this would only happen when you upgrade Go versions.

I can understand the hesitancy for Alpine specifically, but what about Debian?

**Comment by tianon** [comment]
In Debian, we're able to use Go's published release tarballs for all the architectures which support `-race` (`linux/amd64, linux/ppc64le, linux/arm64`), and my understanding is that they thus already include those (they certainly used to - if they don't anymore, that would be an interesting data point).

**Comment by rittneje** [comment]
Ah, just checked for linux/amd64, and you are correct. Did not know that.
