### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries 1.17.8-alpine3.15

### ISSUE THREAD

**Issue by 030** [docker-library/golang#409]
docker pull golang:1.17.8-alpine3.15
1.17.8-alpine3.15: Pulling from library/golang
no matching manifest for linux/amd64 in the manifest list entries

**Comment by tianon** [comment]
https://github.com/docker-library/golang#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

(It's still building -- please be patient! :heart:)
