### ISSUE TITLE
Go 1.18

### ISSUE THREAD

**Issue by fterrag** [docker-library/golang#412]
I saw that https://github.com/docker-library/golang/pull/411 was merged, but I don't see Go 1.18 images available on Docker Hub. Is there any sort of release process that needs to be kicked off to make the latest images available?

Thank you!

**Comment by jauderho** [comment]
Looks like https://github.com/docker-library/golang/actions/runs/1988536721 failed.

**Comment by leighmcculloch** [comment]
It won't show up on Docker Hub until the upstream PR is merged: https://github.com/docker-library/official-images/pull/12045.

**Comment by tianon** [comment]
Indeed, see https://github.com/docker-library/golang#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

GitHub Actions in this repository is just a smoke test (especially since they only support amd64).

**Comment by fterrag** [comment]
@tianon Thank you for explaining the process!
