### ISSUE TITLE
latest, 1, alpine and 1-alpine tags weren't moved to the 1.18 release today

### ISSUE THREAD

**Issue by bytheway** [docker-library/golang#413]
I'm not sure if this issue should be created here or in the official-images repo, but I noticed tonight when trying to pull and build based on the new images released today that `latest`, `1`, `1-alpine` and `alpine` and a handful of other tags are still pointed to 1.17.8 instead of 1.18.0.  

Was this an oversight, or are they lagging purposely?

**Comment by tao12345666333** [comment]
I opened a PR to fix it. #414 

/assign
