### ISSUE TITLE
v1.17.9 Docker Image

### ISSUE THREAD

**Issue by aaronbuchwald** [docker-library/golang#419]
When are the docker images for golang v1.17.9 expected to be released?

**Comment by tianon** [comment]
When Go 1.17.9 is released, we'll update ASAP (https://go.dev/dl/) :sweat_smile:

**Comment by tianon** [comment]
https://github.com/docker-library/golang/commit/ac623657e3a742419f0c5f253ebf2f408fef622e => https://github.com/docker-library/official-images/pull/12227
