### ISSUE TITLE
Alpine images contain /root/.cache/go-build

### ISSUE THREAD

**Issue by jkreileder** [docker-library/golang#422]
The alpine images come with 2.4 MB in /root/.cache/go-build:

```console
$ docker run -it --rm golang:1.17-alpine du -d0 -h /root/.cache/go-build
2.4M	/root/.cache/go-build
```

The Debian images don't have this:
```console
$ docker run -it --rm golang:1.17 du -d0 -h /root/.cache/go-build       
du: cannot access '/root/.cache/go-build': No such file or directory
```

Not sure if this is actually intended or if it is just unneeded weight in the alpine images.

**Comment by tianon** [comment]
Doh, I bet this is a leftover from compiling Go itself (maybe from when the upstream script compiles the stdlib?)

I wonder if `export GOCACHE=off` in https://github.com/docker-library/golang/blob/2c2c1445c95fc87a6246aee51e9d10e86489edf6/1.18/alpine3.15/Dockerfile#L74 would be enough to fix it? :see_no_evil:
