### ISSUE TITLE
`golang:1.19rc2` tag misses `linux/arm64/v8` build

### ISSUE THREAD

**Issue by AlekSi** [docker-library/golang#428]
Compare OS/ARCH lists there:
* https://hub.docker.com/layers/golang/library/golang/1.19-rc/images/sha256-cae786f9b059cc1089b0dcaedf53f10cb505cd274642920562c73954b2664d31?context=explore
* https://hub.docker.com/layers/golang/library/golang/1.19rc2/images/sha256-cae786f9b059cc1089b0dcaedf53f10cb505cd274642920562c73954b2664d31?context=explore

**Comment by yosifkit** [comment]
Some architectures sometimes take a little longer to build depending on what other images are also queued to build.  The `rc2` images now have `arm64v8` available. (https://hub.docker.com/_/golang?tab=tags&page=1&name=rc2)
