### ISSUE TITLE
Should $GOPATH be owned by root?

### ISSUE THREAD

**Issue by NodeGuy** [docker-library/golang#43]
Docker's [best practices states](https://docs.docker.com/articles/dockerfile_best-practices/#user):

> If a service can run without privileges, use USER to change to a non-root user.

I'm wondering if we should make a non-root user to own `/go` and to not open this security can of worms by default.

**Comment by tianon** [comment]
I'm not sure I completely agree that we should chown all of "/go", since we
can't know ahead of time which user to chown it to, but I'd definitely be
+1 to making it "777" by default so that if someone _does_ use a different
user, that new user can access and modify it appropriately.

**Comment by NodeGuy** [comment]
OK, I like your suggestion.

**Comment by yosifkit** [comment]
@NodeGuy, PR made. #44

**Comment by NodeGuy** [comment]
Thanks!

**Comment by NodeGuy** [comment]
Hmm, I'm now getting this warning message from Foreman:

```/var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/process.rb:54: warning: Insecure world writable dir /go/bin in PATH, mode 040777```

It's making me second guess our solution because I plan to run untrusted code in the container.  Maybe we should revert this patch and go back to being owned by `root`, what do you think?

**Comment by NodeGuy** [comment]
No, that warning may be significant on a shared server but probably doesn't matter in a container.  Never mind.
