### ISSUE TITLE
Fail to set up nsswitch.conf

### ISSUE THREAD

**Issue by shunjikonishi** [docker-library/golang#436]
I've copied this Dockerfile and customizing.
It worked last week. However it failed today on this line.

https://github.com/docker-library/golang/blob/master/1.19/alpine3.16/Dockerfile#L14

It seems that now alpine docker image has `/etc/nsswitch.conf` file.

If tha file dones't exist, it works.
However if it exist, test returns 1 and stop.

**Comment by tianon** [comment]
I can't seem to reproduce?

```console
$ docker run --rm --pull=always alpine:3.16 ls -l /etc/nsswitch.conf
3.16: Pulling from library/alpine
213ec9aee27d: Already exists 
Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
Status: Downloaded newer image for alpine:3.16
ls: /etc/nsswitch.conf: No such file or directory
```

**Comment by shunjikonishi** [comment]
hmm, I've verified that.
To be honest, my image is not `FROM alpine:3.16`. That uses from other my docker image(Delived from alpine:3.16) and then run full copy of this file.
nsswitch.conf might be created by other previous process.

However I think the problem is still remain. If nsswitch.conf exists, build failed.

Probably you can reproduce by `RUN touch /etc/nsswitch.conf`

**Comment by shunjikonishi** [comment]
I see.
I've misunderstood your intention. 
I thought the test means, if nsswitch.conf exists, skip to creater that file.

Thanks.
