### ISSUE TITLE
Missing `linux/ppc64le` for `1.19-buster` images

### ISSUE THREAD

**Issue by daezaa** [docker-library/golang#437]
Compare to `1.19rc2-buster`, `linu/ppc64le` arch is not available for `buster` images including `1.19.1-buster`, `1.19.2-buster`  and `1.19.0-buster`
https://hub.docker.com/layers/library/golang/1.19rc2-buster/images/sha256-9efa248a7b72653f9b4aa7427336d22c7d14caaaed302d00415bfaf3af93d0c6?context=explore
https://hub.docker.com/layers/library/golang/1.19.2-buster/images/sha256-ef25fce6779d5b5c4c44c2bde0254ba408ddf499cd3b42081b3685bb23136e35?context=explore

**Comment by yosifkit** [comment]
Debian Buster does not support power since it moved to "LTS". https://github.com/docker-library/official-images/pull/13005 https://wiki.debian.org/LTS

**Comment by daezaa** [comment]
Thanks for the comments, we will take `bullseye` for the replacement.
