### ISSUE TITLE
Make image available in registry other than Docker Hub

### ISSUE THREAD

**Issue by jphx** [docker-library/golang#440]
My company uses anonymous pulls from the Docker Hub registry and, unfortunately, regularly runs into the [Docker Hub rate limit on pulls](https://docs.docker.com/docker-hub/download-rate-limit/).  Is there any chance that the `golang` image could be written also to another registry like https://quay.io/ so that all my Dockerfiles that start with
```dockerfile
FROM golang:latest as builder
```
can be changed to point to Quay or whereever that doesn't such aggressive pull limits?

**Comment by yosifkit** [comment]
If you do a `docker login`, you will have a much higher and individual limit.

The Docker Official Images are also available on Amazon Elastic Container Registry (https://www.docker.com/blog/news-from-aws-reinvent-docker-official-images-on-amazon-ecr-public/ and https://aws.amazon.com/blogs/containers/docker-official-images-now-available-on-amazon-elastic-container-registry-public/). We have no current plans to publish them elsewhere.
