### ISSUE TITLE
feat: add linux/riscv64 image

### ISSUE THREAD

**Issue by ernado** [docker-library/golang#455]
I want to add `linux/riscv64` to supported architectures.

It is not in a [first class port](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports), same as already available `linux/s390x`.

However:
1. This port has no (and probably won't have, until it is first-class) available go binary downloads
2. The `riscv64` port for Debian is unstable, so only available in `sid`.

Ref:
- https://github.com/golang/go/issues/59113
- https://github.com/golang/go/issues/53383

What I can do to make `riscv64` images available?

**Comment by tianon** [comment]
Duplicate of #435 (which is still accurate).

**Comment by ernado** [comment]
Oh, thanks! Missed that one.

**Comment by ernado** [comment]
I will be maintaining a fork until official binaries are available and riscv64 is supported by debian.

Fork of image: https://github.com/go-riscv/docker-library-go
Binaries: https://github.com/go-riscv/go

Everything is built and released by github actions.

Also I'm happy to send invites to [go-riscv](https://github.com/go-riscv) if someone is interested.
