### ISSUE TITLE
Should include pre-build hooks for installing system packages

### ISSUE THREAD

**Issue by creatorzim** [docker-library/golang#46]
I have a project that depends on libaspell-dev, but I can't install this before the ONBUILD commands are run.

Could you include an additional ONBUILD command before the others, or modify go-wrapper, to include [something similar to this](http://blog.dscpl.com.au/2014/12/deferred-build-actions-for-docker-images.html)?
```
if [ -x .docker/action_hooks/pre-build ]; then
  echo " -----> Running .docker/action_hooks/pre-build"
  .docker/action_hooks/pre-build
fi
```

**Comment by tianon** [comment]
I see this as a documentation issue, especially since if we bake this into
the onbuild variant directly it'll re-run the pre-build hook every time the
code changes (ie, reinstall your APT deps every single time you change one
of your ".go" files, which will get old quickly).

What definitely needs better documentation is how to "graduate" from
ONBUILD to introduce more complex logic such as dependency package
installation. :+1:

**Comment by creatorzim** [comment]
Ah, I see. The installed packages can't be cached, so they have to be reinstalled every time.

However, wouldn't this be an issue in any other scenario where one is running `go build` in the Dockerfile? It seems like you would have to rebuild the image even if you didn't use the `-onbuild` as a base, since the application binary needs to be updated before it is run by the container. If so, does this mean that the recommended procedure would be to have an intermediate image that only installs package dependencies? Or to not build code during the image build?

My specific use case is deploying to AWS Elastic Beanstalk with the pre-configured Go environment, so this isn't really an issue for me, but I see how it would be in general. I assume that any Go application with package dependencies use the generic Docker container option instead?

Out of curiosity:
In the hypothetical scenario where ONBUILD commands could be deferred to a granchild, would having an image "in the middle" to install package dependencies solve the issue you bring up?

**Comment by tianon** [comment]
There have been some ideas thrown around regarding letting a `Dockerfile` that's `FROM something:onbuild` actually specify a few instructions before "triggering" the `ONBUILD` instructions, but they haven't gone anywhere yet.  https://github.com/docker/docker/issues/8240 is the issue that comes to mind (from our own @proppy referencing this exact image :heart:).

Essentially, the only "solution" today is something manual like this (which we need to document better):
```Dockerfile
FROM golang:1.4
RUN apt-get update && apt-get install -y some-package
RUN go get -v some.com/package
WORKDIR /go/src/my.com/package
COPY . /go/src/my.com/package
RUN go build -v
CMD ["package"]
```
