### ISSUE TITLE
Alpine 3.18.0 was released yesterday. Could we generate the new images for it?

### ISSUE THREAD

**Issue by AttilaTheFun** [docker-library/golang#461]
https://alpinelinux.org/posts/Alpine-3.18.0-released.html

**Comment by yosifkit** [comment]
Dockerfiles are already updated: https://github.com/docker-library/golang/pull/460

https://github.com/docker-library/golang/tree/713124c10e228b178e92ecf949e86c16bc3f3057#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
