### ISSUE TITLE
libc.so.6: version `GLIBC_2.3x' not found (from binaries built in new bookworm based images but run on older distros)

### ISSUE THREAD

**Issue by zhiweiyin318** [docker-library/golang#466]
I used golang:1.20 which built yesterday to build my image, my image failed to run with the errors 
```
/placement: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /placement)
/placement: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /placement)
```
the golang:1.20 digest: golang@sha256:3164c26b2e170b18e2325aa0554699e7bb19a658333601659c04838855897f7a

when I changed to 1.20.4, everything is ok.

**Comment by tianon** [comment]
This is unfortunately not unexpected.  See also https://github.com/docker-library/official-images/pull/14857#issuecomment-1591968024:

> They can also specify the Debian version of the Golang images (only the two most recent are updated/supported): `golang:1.20.5-bullseye` or `golang:1.20.5-bookworm` (and `golang:1.20-bullseye`, etc).

> If you don't need `cgo` in your binary, it should also work to specify `CGO_ENABLED=0` explicitly.

**Comment by zhiweiyin318** [comment]
thanks @tianon
