### ISSUE TITLE
Please add the tzdata package to all golang:alpine images, making it convenient to set the timezone using TZ=UTC.

### ISSUE THREAD

**Issue by himonster1** [docker-library/golang#477]
tzdata is included by default in Debian systems, but it is not included in Alpine.

**Comment by tianon** [comment]
See https://hub.docker.com/_/golang, especially:

> To minimize image size, additional related tools (such as `git`, `gcc`, or `bash`) are not included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar). See also [docker-library/golang#250 (comment)](https://github.com/docker-library/golang/issues/250#issuecomment-451201761) for a longer explanation.

**Comment by tianon** [comment]
I'll also note that we don't _intentionally_ install `tzdata` in the Debian-based variants -- it is included because it is part of the base image we're `FROM` (and if it were to remove it, we would no longer include it).

**Comment by himonster1** [comment]
Thanks, but you seem to have misunderstood me, I want tzdata installed, I need it, I need tzdata

**Comment by tianon** [comment]
Right, sorry for not being more clear; I'm suggesting you should `RUN apk add --no-cache tzdata` in your own `Dockerfile` -- our not including `tzdata` is intentional, and we do not plan to change that.
