### ISSUE TITLE
Add `-debian12` tags in addition to `-bookworm`

### ISSUE THREAD

**Issue by corani** [docker-library/golang#478]
I'm using Renovate to keep my dependencies up-to-date. When using `golang:1.20.6-alpine3.18` this correctly creates an update in case either Golang (`1.20.6`) or Alpine (`3.18`) is updated. However, this doesn't work for the Debian images (for obvious reasons). Would it be possible to generate e.g. `golang:1.20.6-debian12.1` tags in addition to the `-bookworm` tags?

**Comment by tianon** [comment]
Unfortunately, this isn't something we plan to do (and is a common pattern across a very large number of other Docker Official Images too, so probably something Rennovate ought to handle somehow).
