### ISSUE TITLE
Missing architectures on some 1.21.0 images

### ISSUE THREAD

**Issue by alubbock** [docker-library/golang#480]
On the [golang Dockerhub page](https://hub.docker.com/_/golang/tags), some 1.21.0 images are not being generated for all architectures. E.g., at the time of writing:

* `latest` is generated for 10 architectures
* [1.21.0-bullseye](https://hub.docker.com/layers/library/golang/1.21.0-bullseye/images/sha256-99e4c23f67e9b68ac20a2bfc036321bc3eb4c2cdb4681f6403f81bcf12a93d66?context=explore) has been generated for 3 architectures, versus 8 for [1.20.0-bullseye](https://hub.docker.com/layers/library/golang/1.20.0-bullseye/images/sha256-729f2ed830b2e1b8df4d6110eaea96acd48650e994522199b4a807d201f16325?context=explore)
* [1.21.0-alpine3.17](https://hub.docker.com/layers/library/golang/1.21.0-alpine3.17/images/sha256-81e88b4630cd740a738adddd2974331e4790f0ea449fcaef577d54b19d3b5ffb?context=explore) has only been generated for `linux/arm/v7`, versus 7 architectures for [1.20.0-alpine3.17](https://hub.docker.com/layers/library/golang/1.20.0-alpine3.17/images/sha256-e4a7719fce4dabe658cee60c098db43a7f31730f23cf53c45fa7a14c588befa6?context=explore).

**Comment by yosifkit** [comment]
They'll be there eventually. The reason for `latest` having more is that it is still pointing to `1.20` images for architectures that aren't done building (https://github.com/docker-library/golang/issues/416#issuecomment-1078493678).

See also https://github.com/docker-library/official-images/pull/15164#issuecomment-1670430593

And https://github.com/docker-library/golang/tree/d1ff31b86b23fe721dc65806cd2bd79a4c71b039#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet -> https://github.com/docker-library/faq/tree/4c89e2217c5512d2a9c6efe36f488a6126541a0c#an-images-source-changed-in-git-now-what
