### ISSUE TITLE
Add `1.X-debian-stable` type alias

### ISSUE THREAD

**Issue by Jorropo** [docker-library/golang#485]
Hey [I am maintaining some software](https://github.com/ipfs/kubo/blob/master/Dockerfile) and I recently noticed that some of our docker images were built with the wrong version of go (`1.19.10` when `1.19.12` was the latest on the `1.19` branch at the time).
AFAIT this is because buster was no longer supported and you switched to bullseye and bookworm instead.
So I should have used `1.19-bulleyes` or `1.19-bookworm` images, however our docker deployment is automated and we only really look at it when bumping the major go version (we don't do that automatically due to regressions in the go std https://github.com/ipfs/kubo/issues/10065)

As a maintainer that rely on your work it would make my life easier if you could provide an alias along the lines of `1.X-debian-stable` where X is `20` or `21` to take the current releases of go as example. Exactly like you already do for `-alpine`.

I guess for consistency the full matrix of precision should also be supported like you do for alpine so:
- `1.X.Z-debian-stable`
- `1.X-debian-stable`
- `1-debian-stable`
- `debian-stable`

But I personally don't need it.

---

I'm not sure about `-debian-stable`, `-debian` or something else could very well be a better name.

Thx :slightly_smiling_face:

**Comment by yosifkit** [comment]
Debian is the default variant and the current stable (`bookworm`) is the default release.  So we already have `1.21.0, 1.21, 1, latest` and `1.20.7, 1.20` tag sets to choose the newest stable Debian with go `1.21` (or `1` or `1.20`).

**Comment by Jorropo** [comment]
I see, I missed the `Shared Tags` section.

Technically debian stable and bookworm are different (`stable` use a different `sources.list` which implicitly rolls to the next debian stable release) but I don't need it in my case.

Thx
