### ISSUE TITLE
Feature Request: "-tags" support in go-wrapper

### ISSUE THREAD

**Issue by gmlewis** [docker-library/golang#49]
I would like to standardize on using the `golang` Dockerfile for Go apps running on [Managed VMs](https://cloud.google.com/appengine/docs/managed-vms/), but to do this, I need to pass `-tags appenginevm` to `go build` and it appears that the current `go-wrapper` does not yet support the [tags](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies) flag.

Before I start adding this to `go-wrapper`, @tianon , does this sound like something that might be accepted?

I was thinking that a developer's Dockerfile could add a line like this:
```dockerfile
ENV GOTAGS 'tag list'
```
and then `go-wrapper` would add `-tags 'tag list'` to the `go build` command.

**Comment by gmlewis** [comment]
It looks like I can just add extra args to the end of run.  Sorry for the bogus report.
Closing.

**Comment by tianon** [comment]
Yeah, I usually don't use "go-wrapper" directly if I'm not using the
"onbuild" images, which I don't usually use because I like to "go get" my
dependencies more explicitly before I "COPY" my code in so I get good
caching.
