### ISSUE TITLE
Something is not right with `GOARM`

### ISSUE THREAD

**Issue by AlekSi** [docker-library/golang#494]
`GOARM` value is correct for [`linux/arm/v5` variant](https://hub.docker.com/layers/library/golang/1.21.4/images/sha256-bc69875a9f3af085bd1ea11a44283b46746ef026301552e3c85de7140ad04e90?context=explore):

```
$ docker rmi golang; docker run -q --rm --platform=linux/arm/v5 golang go env GOARM
[…]
5
```

However, it is not correct for [`linux/arm/v7`](https://hub.docker.com/layers/library/golang/1.21.4/images/sha256-fbd184e3e10f5a3e30e01fe8aefb05d7950e0e9a59a6fd0995691b4c239760f3?context=explore):

```
$ docker rmi golang; docker run -q --rm --platform=linux/arm/v7 golang go env GOARM
[…]
6
```

**Comment by yosifkit** [comment]
Upstream go only publishes `armv6` binaries (https://go.dev/dl/), so that is what is currently used:
https://github.com/docker-library/golang/blob/e787bff89247be4ce5a642335fd94e866a188902/versions.sh#L77

**Comment by AlekSi** [comment]
> determine whether recompiling for GOARM=7 is worthwhile

I think it is worth doing it just to avoid confusion. I used that image as a base to build ARM v7 binaries that turned out to be v6. It means that every user of that image has to be aware of it and apply a workaround.

**Comment by tianon** [comment]
Is there a significant performance difference between compiling with `GOARM=6` vs `GOARM=7`?
(I don't think the Go project itself would've chosen lightly to only publish v6.)

More generally, I'd honestly recommend users should always be explicit about the full set of `GOOS`, `GOARCH`, and `GOARM`, especially in the case of building binaries for publishing.

**Comment by AlekSi** [comment]
> I'd honestly recommend users should always be explicit about the full set of GOOS, GOARCH, and GOARM, especially in the case of building binaries for publishing.

That somewhat contradicts the recommendations of the Go team. There is no need to set those variables if compilation is performed on the host – autodetection works in this case. And I would expect BuildKit/QEMU-powered builds to be indistinguishable from builds on the host – and they would be, if not this issue with the base image.

**Comment by tianon** [comment]
> That's true for Go, too, but not for this Docker image.

For Go built from source, yes, but not for Go downloaded from https://go.dev/dl/ (which only publishes armv6, so that's what you'd download/use on armv7).

However, I remembered today that 1.21 has `go.env` so we can override this default for the install without recompiling, so I'm going to make a PR doing that shortly. :eyes:
