### ISSUE TITLE
`golang:1.21.7` does not have an `linux/amd64` image

### ISSUE THREAD

**Issue by oliver-goetz** [docker-library/golang#508]
Instead it has 2 `windows/amd64` images 😅 

![Screenshot 2024-02-07 at 00 43 25](https://github.com/docker-library/golang/assets/47362717/3304093f-9070-4fb9-9caa-b69718d482dd)

**Comment by tianon** [comment]
Yep, the builds are still in progress -- those Windows images are two different versions of Windows (because the kernel version of the host has to match the container, in the ideal case).

**Comment by oliver-goetz** [comment]
thanks 😄
