### ISSUE TITLE
golang:1.22-alpine is linux/386 instead of linux/amd64

### ISSUE THREAD

**Issue by maxatome** [docker-library/golang#510]
golang:1.21-alpine is well linux/amd64.

Does the building of golang:1.22-alpine occurred on a linux/386 platform?

From a linux/x86_64:
```
❯ docker run -it --rm golang:1.22-alpine go version 
Unable to find image 'golang:1.22-alpine' locally
1.22-alpine: Pulling from library/golang
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

**Comment by stvoidit** [comment]
https://github.com/docker-library/golang/issues/511#issuecomment-1931959053

I ran into the same problem, so I added an architecture refinement to my Dockerfile.
I think this may help to avoid a similar problem.
