### ISSUE TITLE
Despite build passed, amd64 is missing on golang:1.22.0-alpine3.18

### ISSUE THREAD

**Issue by poush** [docker-library/golang#512]
Hello, 

I was trying to update our images with new tag `golang:1.22.0-alpine3.18` but our pipelines failed and we realise that `amd64` arch is missing from `golang:1.22.0-alpine3.18` tag on dockerhub. 

I had a quick look to your build, it seems like the build passed and the image pushed but even then as you can see here in the screenshot below, amd64 is missing.

<img width="630" alt="Screenshot 2024-02-07 at 14 47 42" src="https://github.com/docker-library/golang/assets/1812082/4b6fe3bf-ffc1-4437-be51-27cc0293d1bf">

Could you look into it?

**Comment by Merovius** [comment]
Just had to give it a bit. It seems to be there, now.

**Comment by poush** [comment]
ah yes it's there now, thanks!
