### ISSUE TITLE
Add go-task to this imge

### ISSUE THREAD

**Issue by MisterMX** [docker-library/golang#513]
This library defaults to `make` as the standard build tool. However, https://github.com/go-task/task emerged as a vital successor that provides a more modern interface and is easier to use and understand.

Adding `task` to the standard Go images would make using it much easier since devs don't have to provide a custom image built on top of it.

And since the binary is very small (only around 5-6 MB) it would not drastically increase image size.

**Comment by tianon** [comment]
I'm sure `task` is great, but this is the first time I've ever heard of it. :innocent:
I don't think it's likely to be pervasive enough to warrant adding to the images by default, unfortunately. :sweat_smile:

If we had explicit endorsement/recommendation from the Go upstream project that ~everyone ought to use this (or at least consider doing so), we'd be willing to reconsider, but as-is I'm afraid this isn't something we're planning to add. :bow: :heart:
