### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by zrml** [docker-library/golang#52]
I'd love to have an sshd built in the image.
It seems a reasonable request to me...
thank you

**Comment by tianon** [comment]
With `docker exec` being an official feature now, what's the rationale for having `sshd` installed inside the container?

Additionally, why not just create a short `Dockerfile` that's `FROM` this one and adds whatever you need?  Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with whatever you need added in.

```Dockerfile
FROM golang:1.4
RUN apt-get update && apt-get install -y openssh-server && rm -rf /var/lib/apt/lists/*
```

**Comment by zrml** [comment]
IO with exec is not  like a normal shell. Some software cores.
Furthermore I can have a team of developers, securely accessing a cloud development container...
Installing ssh server is half the story.
At present I'm using Tutum that have a nice, simple & flexible implementation of CentOS 7 + sshd
I understand what you're saying...
it'd be easier to just have it in there for developers... who are inherently lazy :-)

thanks

**Comment by waterlink** [comment]
I doubt it is laziness, it is just idiomatic way to build docker containers. 

+ Being able to `ssh` to container kills the whole idea of `immutable` deployments.

**Comment by zrml** [comment]
You're right about the immutable infrastructure and I love the whole concept and practicality of it. This tells me though, that you're possibly only looking at it (this particular go container) from a deployment point of view, while I'm looking at it from a development point of view.. hence i need that service right in there.
However there is another point to this :-) 
My container -even in a development environment is immutable. I ssh, cloud9-connect (from another container etc.) BUT the outcome of our work is on a host volume. Therefore, as a consequence, my ssh container is totally immutable. Just offering an extra service I need.

I guess the discussion could be going on forever... :-)

It's a good point that made me think.

**Comment by alex-fedorov** [comment]
@zrml You can create your own development container easily, like `zrml/golang-dev` which will use `FROM golang:1.X` statement in dockerfile. And this goes well with single responsibility principle:

- `library/golang` is for deployment;
- `zrml/golang-dev` is for development.

**Comment by zrml** [comment]
it's an option. Thanks waterlink :)
