### ISSUE TITLE
missing most architectures from golang:1.22.5

### ISSUE THREAD

**Issue by ldemailly** [docker-library/golang#525]
For linux it only has 386

It does have 2 windows amd64 though so there is that :)

<img width="444" alt="Screenshot 2024-07-02 at 5 43 35 PM" src="https://github.com/docker-library/golang/assets/3664595/c6098c6b-13b0-4caf-8d2d-5d32a84b13cc">

is it stuck somewhere?

for ref expected/1.22.4:

<img width="445" alt="Screenshot 2024-07-02 at 5 46 09 PM" src="https://github.com/docker-library/golang/assets/3664595/c4df6aca-863f-43fc-9d0b-f096b8e3a4f8">

Golang's https://go.dev/dl/ release was >5h ago

Edit: link: https://hub.docker.com/layers/library/golang/1.22.5/images/sha256-c8715e797d0705204fdeeaf791773c80d5a036c021779984b4c817d84f9b19cb

**Comment by cpanato** [comment]
looks like we have all now https://hub.docker.com/_/golang/tags?page=&page_size=&ordering=&name=1.22.5

**Comment by ldemailly** [comment]
Thanks, though mips is still not there.

Can you shed some light on 2 things:

- How can the content change yet the sha of the index not change?

- Why is it taking so long?

**Comment by LaurentGoderre** [comment]
The sha of the index does change when the content change. The tag just points to a new index when that happens.

As for why it takes so long, we have a lot of images and when a base image like debian changes and every dependant image need to be rebuilt, the queue gets pretty long.

**Comment by ldemailly** [comment]
ic indeed, yesterday it was golang:1.22.5@sha256:45c516d2adb456d6a0ca3cc5172013abbf65d5152dbd5f9edffaa63fbf96a96d
and today it's 
golang:1.22.5@sha256:1a9b9cc9929106f9a24359581bcf35c7a6a3be442c1c53dc12c41a106c1daca8

what confused me is there is what looks like a sha in the url: https://hub.docker.com/layers/library/golang/1.22.5/images/sha256-c8715e797d0705204fdeeaf791773c80d5a036c021779984b4c817d84f9b19cb
and that one doesn't change... or... is aliased magically in backend?


About taking so long, I understand there is a ton of things running but maybe security updates of a major language should be prioritized together to be "finished" (ie finish golang before starting others etc)

**Comment by tianon** [comment]
I don't fully understand why Hub puts a digest in those URLs, but I _believe_ that's the digest of the image manifest of the specific architecture you're viewing (which defaults to `linux/amd64`, IIRC).

We are exploring ways we could improve the priority ordering of builds, but there are a lot of complicating factors, not the least of which is that not all of our supported architectures are "created equally" (for example, `mips64le` is typically _very_ slow).

**Comment by whalelines** [comment]
At present, we do not delete untagged manifests in the DOI (library) namespace.

**Comment by ldemailly** [comment]
you closed it as complete but... `linux/mips64le` is still missing compared to 1.22.4 - or is that deprecated?

**Comment by whalelines** [comment]
The linux/mips64le will show up when its build is complete. Since you opened this issue and communicated you did not need that image, I closed the issue.

**Comment by ldemailly** [comment]
Same today with 1.22.7 :-(

If the security fixes were 0 days or critical, it'd be a fairly serious problem.
