### ISSUE TITLE
golang:1.23-alpine update to 1.23.2 failed; broken link on docker hub page

### ISSUE THREAD

**Issue by kb-sp** [docker-library/golang#537]
* golang:1.23-alpine remains at 1.23.1 even after the workflows here seem to have passed. Is there a long lag that I just haven't noticed before?
* There is a link at https://hub.docker.com/_/golang for [the Docker Community Slack⁠](https://dockr.ly/comm-slack) which is broken.

Thanks!

**Comment by yosifkit** [comment]
https://github.com/docker-library/golang?tab=readme-ov-file#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet -> https://github.com/docker-library/official-images/pull/17657; So, builds are in progress and should be on Docker Hub soon.

---

The broken Docker Community Slack link is being looked at and will resolve correctly once fixed.

**Comment by kb-sp** [comment]
Thanks, @yosifkit! Do you know if there's a way to monitor the official-images build process (which I assume is owned by Docker?)

**Comment by yosifkit** [comment]
Yeah, most of it happens via our [Docker Official Images' Jenkins instance](https://doi-janky.infosiftr.net/) and is described in https://github.com/docker-library/faq/blob/36d5fc9264cbe8a412323784bd4d3c83bae83fed/README.md#an-images-source-changed-in-git-now-what.
