### ISSUE TITLE
Two SHA keys found for golang:1.23-bullseye

### ISSUE THREAD

**Issue by keshavbhattad** [docker-library/golang#538]
When downloading docker image, we found that there are two SHA keys found for golang:1.23-bullseye -
- 9ae7327523e2e170d9514ea6ee5dffd22d2a6cb7aca29139e1e0e862ea6da475
- ebaf58d74f200c27dce0181203a1347e41b5c159c9aa0517a95bec594aabbde4

This has been leading us in error while loading native go plugins within the host process. Can you please get this checked and provide resolution if any?

Thanks

**Comment by keshavbhattad** [comment]
I guess there was a change in golang version from 1.23 to 1.23.2 yesterday (Ref - https://github.com/docker-library/golang/commit/89de06f6dd2c4edb29f33bb7270bdcc8000cf58a) which is causing this issue. Can you help in correctly mentioning how can we keep our base docker image to 1.23.1 (former)
Current usage -

Dockerfile
```
FROM golang:1.23-bullseye AS builder
...
```

**Comment by dagood** [comment]
> Can you help in correctly mentioning how can we keep our base docker image to 1.23.1 (former)

There are tags available that include the `.1` as well, check https://hub.docker.com/_/golang/ to see the way the tags are laid out. In this case you're looking for:

```Dockerfile
FROM golang:1.23.1-bullseye
```

**Comment by keshavbhattad** [comment]
Oh my bad. Pinning it to `1.23.1` is working fine.
Thanks a lot!

Closing this issue
