### ISSUE TITLE
stderr/stdout not redirected properly

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker-library/golang#60]
I have a Go program that writes to both stderr and stdout. If I run this within `golang:1.5-onbuild` base image, the output I get from the container when I attach to stdout of the container (using `-i -t -a stdout`) also contains the output from program's stderr.

I'm guessing this is happening because of `go-wrapper`. Should this be fixed or is it by design?

**Comment by tianon** [comment]
That's Docker itself:
```console
$ docker run -it -a stdout debian bash -c 'echo >&2 test'
test
```

**Comment by tianon** [comment]
Compare to:
```console
$ docker run -a stdout debian bash -c 'echo >&2 test'
```

**Comment by ahmetalpbalkan** [comment]
Oh that's sad. Any ideas why this is the case?

**Comment by tianon** [comment]
Yeah, I'm not sure.  I want to say there was an issue discussing this a while ago, but I can't seem to find it now.  Something about either `-i` or `-t` assumes attachment (and IIRC there was even some discussion about removing `-a` entirely).

**Comment by ahmetalpbalkan** [comment]
@tianon thanks for the input. Looks like removing `-t` solves it:

```sh
$ #stdout:
$ docker run -i -a stderr debian bash -c 'echo >&1 test' test
$ docker run -i -a stdout debian bash -c 'echo >&1 test' test
test
$ #stderr:
$ docker run -i -a stdout debian bash -c 'echo >&2 test' test
$ docker run -i -a stderr debian bash -c 'echo >&2 test' test
test
```
