### ISSUE TITLE
Can go-wrapper be copied to another repo?

### ISSUE THREAD

**Issue by gmlewis** [docker-library/golang#62]
Hi @tianon ,

Can "go-wrapper" from this repo be copied to another base image repo?

Specifically, we would like to use it for building the base image for Go on App Engine apps.
The repo is here:
https://github.com/GoogleCloudPlatform/golang-docker

Can I simply copy it to the "base" subdirectory of this repo, or are there steps that I must take before doing the copy?

Thanks!
-- Glenn

**Comment by tianon** [comment]
There _might_ be license concerns, but IANAL.  From a technical
perspective, it should "just work". :smile:

**Comment by tianon** [comment]
You could also instead `curl` it in the `Dockerfile`, like we do for `hack/dind` in the `docker` image: https://github.com/docker-library/docker/blob/251cf235760a2ba6db1cf1ddc8ccb3d4da5ec99d/1.8/dind/Dockerfile#L13-L16

**Comment by gmlewis** [comment]
Ah, great!  Thanks, Tianon!
Closing.
