### ISSUE TITLE
Cross builder for 1.5

### ISSUE THREAD

**Issue by j16sdiz** [docker-library/golang#63]
Cross builder for 1.5 needed

**Comment by tianon** [comment]
Actually, check out http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5 -- an explicit `golang:cross` image is no longer necessary with Go 1.5. :+1: :smile:

**Comment by j16sdiz** [comment]
If this is the case, can you tag `1.5` with `1:cross` too?
This will save us lots of script changes.

**Comment by tianon** [comment]
Yeah, I suppose adding "cross" as an alias for 1.5 makes sense.

**Comment by tianon** [comment]
Hmm, I thought it'd be as easy as adding another 1-line alias but it's going to require slightly more invasive changes in `generate-stackbrew-library.sh` so I'm back on the fence for this one. :disappointed:

**Comment by fboyer** [comment]
I would suggest to update the description on docker hub as it still refers to the "cross" tag for cross-compiling.

**Comment by tianon** [comment]
IMO, the docs updates for this (https://github.com/docker-library/docs/issues/523) are sufficient to make it clear that cross-compilation is well-supported in all the default images without explicit tags.  Sorry for the delay, and thanks for reporting!
