### ISSUE TITLE
/go is owned by root

### ISSUE THREAD

**Issue by SvenDowideit** [docker-library/golang#65]
and has no write permissions for other users

which means you can't run `go get` in a container running as non-root fails.

```
sven@3a8fb991af94:~$ docker run --rm -it  -v /home/sven/go:/go --volumes-from app_shell_1 -u 1000 golang:1.4-cross bash
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
I have no name!@492649734cdd:/go$ 
I have no name!@492649734cdd:/go$ ls
I have no name!@492649734cdd:/go$ go get github.com/spf13/hugo
package github.com/spf13/hugo: mkdir /go/src: permission denied
I have no name!@492649734cdd:/go$ ls
I have no name!@492649734cdd:/go$ ls -la
total 8
drwxr-xr-x  2 root root 4096 Sep 14 15:01 .
drwxr-xr-x 53 root root 4096 Sep 14 15:01 ..
```

**Comment by tianon** [comment]
Hmm, that's strange, because we explicitly set `/go` to be `777`: https://github.com/docker-library/golang/blob/137c5d9cacd3a2be7cc07be3c6bdcfddce737934/1.4/Dockerfile#L22

(and it seems to be OK here:)

```console
$ docker pull golang:1.4-cross
1.4-cross: Pulling from library/golang
843e2bded498: Already exists 
8c00acfb0175: Already exists 
8b49fe88b40b: Already exists 
20b348f4d568: Already exists 
2303385b9443: Already exists 
5bf7351f1d1e: Already exists 
caec51cb121f: Already exists 
1c9ff25590e3: Already exists 
18ffd14866b9: Already exists 
4c6c0bc713ad: Already exists 
43043f47da83: Already exists 
69601af4c2db: Already exists 
32c44ee1812a: Already exists 
c5a2538d92ec: Already exists 
8b962a60c958: Already exists 
43e937dd67bf: Already exists 
8c988591f167: Already exists 
Digest: sha256:48b27de9ba237aa5483075fa6daecade635d29768830000d6c42e6bc560fd8f5
Status: Image is up to date for golang:1.4-cross
$ docker run -it --rm golang:1.4-cross
root@380cd66ca24d:/go# ls -la    
total 16
drwxrwxrwx 4 root root 4096 Sep 10 10:32 .
drwxr-xr-x 1 root root 4096 Sep 14 16:21 ..
drwxrwxrwx 2 root root 4096 Sep  9 21:46 bin
drwxrwxrwx 2 root root 4096 Sep  9 21:46 src
```

**Comment by md5** [comment]
@tianon Seems like there could be issues if a subdirectory like `/go/src/github.com` were created by `root` and then a non-`root` user tried to create a subdirectory of that, given the default `umask`. It possible that having a `go` group and a `setgid` could help to some extent, but it wouldn't work recursively.

I'm not sure there's a good way to solve this other than only supporting a single non-`root` user for all code installation.

**Comment by md5** [comment]
That doesn't explain why @SvenDowideit isn't even seeing the right permissions on `/go/src` though.

**Comment by md5** [comment]
Oh, wait, he's mounting `/go` from a host directory.

**Comment by tianon** [comment]
Well, as long as we aren't mixing "root" and then "non-root" usage, it
should work fine as-is for both uses, right?

**Comment by tianon** [comment]
Hah, nice catch @md5. :+1:

**Comment by md5** [comment]
@tianon Should be.

**Comment by md5** [comment]
For a second I wondered why `/home/sven/go` would be `root`-owned, but it looks like the "host" directory in this case is actually inside a container.

**Comment by SvenDowideit** [comment]
yup, good catch., closing.
