### ISSUE TITLE
golang:1.5.1-alpine image is missing go-wrapper

### ISSUE THREAD

**Issue by zhaytee** [docker-library/golang#70]
The onbuild and wheezy variants include the go-wrapper script, but the alpine one does not. It seems to be missing the COPY command in the Dockerfile.

**Comment by Gyscos** [comment]
`alpine:3.2` also does not have `git` pre-installed, unlike `buildpack-deps:jessie-scm`, so many `go-wrapper download` would not work.

**Comment by tianon** [comment]
I contemplated including it, but we purge `bash` so the script wouldn't even run as-is (and it really mostly exists for the `onbuild` variant anyhow).

**Comment by xanadros** [comment]
I find the go-wrapper utility very helpful in having a single docker file for all my go apps, and it just works.  Perhaps I'm using it wrong, but it would be nice to have in the alpine image as well.

That being said, I wrote a POSIX compliant version of the script (minimal changes that were mostly around array usage for the install and download commands).  Any interest in me submitting a pull request for that?

FWIW, I used the posix array trick found [here](http://www.etalabs.net/sh_tricks.html) under the "Working with arrays" section.

**Comment by tianon** [comment]
I would definitely be keen to see it!  (POSIX shell would make this much more palpable to reconsider including indeed)

**Comment by xanadros** [comment]
Submitted PR #89 
Any feedback is welcomed.

**Comment by xanadros** [comment]
@tianon don't forget that PR #98 closes this issue too.

**Comment by yosifkit** [comment]
Thanks @xanadros
