### ISSUE TITLE
can't load package: package app: no buildable Go source files in /go/src/app

### ISSUE THREAD

**Issue by jgolio** [docker-library/golang#73]
Dockerfile has a single line: "FROM golang:onbuild"

Get the following error:

jgolio@joe-Precision-WorkStation-T5500: > docker build -t golang .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM golang:onbuild
onbuild: Pulling from golang
6d1ae97ee388: Already exists 
8b9a99209d5c: Already exists 
2e05a52ffd47: Already exists 
80887d145531: Already exists 
ec064956c4f0: Already exists 
c8a688c71293: Already exists 
03f519453f95: Already exists 
b449de9eb16c: Already exists 
7ab9945f3cbe: Already exists 
7cb2cf0c147e: Already exists 
b56020e12f7a: Already exists 
1c3154f0cc14: Already exists 
d556268f76ae: Already exists 
0eca3aede538: Already exists 
cf249b900631: Already exists 
e76f6354d97b: Already exists 
3b257c27c645: Already exists 
d9d76b3f6346: Already exists 
cce7e8018ea3: Already exists 
040bcbc1f0fe: Already exists 
golang:onbuild: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:48a136c23844f202883c7181a86383098da6900153099daf5a0b3556af6ae62c
Status: Downloaded newer image for golang:onbuild
# Executing 3 build triggers
Trigger 0, COPY . /go/src/app
Step 0 : COPY . /go/src/app
Trigger 1, RUN go-wrapper download
Step 0 : RUN go-wrapper download
 ---> Running in 445b2396dc17
+ exec go get -v -d
can't load package: package app: no buildable Go source files in /go/src/app
The command '/bin/sh -c go-wrapper download' returned a non-zero code: 1

Note that I'm pretty much a Docker and Golang novice, so I'm thinking it's something fairly stupid that I'm doing.

**Comment by tianon** [comment]
Is the application you're trying to build open source so we could take a
look?  My guess is that the top-level package of it isn't actually
something with a "func main", so you'll have to write something slightly
more involved than just using the onbuild image.

**Comment by jgolio** [comment]
I was simply trying to follow the instructions in https://hub.docker.com/_/golang/. I've tried using golang:onbuild, golang:1.3-onbuild, golang:1.6-onbuild and they all do the same thing.

**Comment by tianon** [comment]
Right, I'm saying that your application probably isn't structured such that
your "func main" package is at the top-level, so you're going to need a
slightly more complex Dockerfile -- can you share more details about your
application?  Is it private, or open source?  Which package is "func main"
in?

**Comment by jgolio** [comment]
I think I'm starting to understand. This time, I took the 1.6-onbuild Docker file from github and built it and that seemed to work. I then tried started the container with /bin/bash so that I could look around. I see there is nothing in /go/src/app, so I created a sample hello world app in there and from the container, I ran "go run hello.go" and it worked.

**Comment by jgolio** [comment]
I have things pretty much working now. I figured out how to mount a volume on my host to the golang container and build apps using "go build". Thanks for the help.
