### ISSUE TITLE
alpine container has 36M of stuff from bootstrap in it

### ISSUE THREAD

**Issue by client9** [docker-library/golang#77]
Hello docker-library/golang.

Thanks for making a combo alpine/golang.  I find it very useful.  I did notice one oddity.  it appears it contains 36M of leftover bootstrap code, that I suspect can be deleted to the delight of everyone.

The alpine container uses gcc and golang 1.4 to bootstrap and build golang latest.

It appears the bootstrap is meant to be deleted after use, since in the in the Dockerfile, I see 

```
	&& rm -rf /usr/local/bootstrap \
```

But in `/usr/local/go/pkg` I see 36M of other bootstrap leftovers.

```sh
/usr/local/go/pkg # du -c -m bootstrap
0	bootstrap/src/bootstrap/asm/internal/arch
0	bootstrap/src/bootstrap/asm/internal/asm
0	bootstrap/src/bootstrap/asm/internal/lex
0	bootstrap/src/bootstrap/asm/internal/flags
0	bootstrap/src/bootstrap/asm/internal
0	bootstrap/src/bootstrap/asm
0	bootstrap/src/bootstrap/link/internal/arm
0	bootstrap/src/bootstrap/link/internal/amd64
0	bootstrap/src/bootstrap/link/internal/arm64
0	bootstrap/src/bootstrap/link/internal/ppc64
0	bootstrap/src/bootstrap/link/internal/x86
0	bootstrap/src/bootstrap/link/internal/ld
1	bootstrap/src/bootstrap/link/internal
1	bootstrap/src/bootstrap/link
0	bootstrap/src/bootstrap/internal/gcprog
0	bootstrap/src/bootstrap/internal/obj/arm
0	bootstrap/src/bootstrap/internal/obj/arm64
0	bootstrap/src/bootstrap/internal/obj/ppc64
0	bootstrap/src/bootstrap/internal/obj/x86
1	bootstrap/src/bootstrap/internal/obj
1	bootstrap/src/bootstrap/internal
0	bootstrap/src/bootstrap/compile/internal/arm
0	bootstrap/src/bootstrap/compile/internal/amd64
1	bootstrap/src/bootstrap/compile/internal/gc
0	bootstrap/src/bootstrap/compile/internal/arm64
0	bootstrap/src/bootstrap/compile/internal/big
0	bootstrap/src/bootstrap/compile/internal/ppc64
0	bootstrap/src/bootstrap/compile/internal/x86
2	bootstrap/src/bootstrap/compile/internal
2	bootstrap/src/bootstrap/compile
4	bootstrap/src/bootstrap
4	bootstrap/src
18	bootstrap/bin
1	bootstrap/pkg/linux_amd64/bootstrap/asm/internal
1	bootstrap/pkg/linux_amd64/bootstrap/asm
2	bootstrap/pkg/linux_amd64/bootstrap/link/internal
2	bootstrap/pkg/linux_amd64/bootstrap/link
2	bootstrap/pkg/linux_amd64/bootstrap/internal/obj
2	bootstrap/pkg/linux_amd64/bootstrap/internal
9	bootstrap/pkg/linux_amd64/bootstrap/compile/internal
9	bootstrap/pkg/linux_amd64/bootstrap/compile
14	bootstrap/pkg/linux_amd64/bootstrap
14	bootstrap/pkg/linux_amd64
14	bootstrap/pkg
36	bootstrap
36	total
```
I don't see this bootstrap directory in the other golang binary downloads .

Useful? Intentional? Mistake? 

I'd love to see `&& rm -rf /usr/local/bootstrap \` added and save 36M if possible.

thanks all!

nickg

p.s. the `/usr/local/go/test` directory (10MB) also looks suspicious, but I'm less certain about it.

**Comment by yosifkit** [comment]
Sounds good to me; I'm testing it with #78.

**Comment by client9** [comment]
Hi again @yosifkit @tianon   Only partially related to this, but what is the release process for the official golang repos?  I understand you need to make a pull request back to docker to update the revision.  I imagine you are quite busy, so no rush, just wondering if there is a formal process.
Regards, --n

**Comment by yosifkit** [comment]
The process just involves a PR to [official-images](https://github.com/docker-library/official-images) updating the [golang](https://github.com/docker-library/official-images/blob/b83ebc6340768af6327084c8549d94b9e5cd834a/library/golang) file whose contents are generated from the handy [generate-stackbrew-library.sh](https://github.com/docker-library/golang/blob/0d4ac4ae8c8f859cf355045bf44bac7602ab7248/generate-stackbrew-library.sh).  I just made one for this fix and some other image updates: https://github.com/docker-library/official-images/pull/1354.

**Comment by client9** [comment]
oh thanks @yosifkit   just learning how this all works...
