### ISSUE TITLE
questions about alpine images

### ISSUE THREAD

**Issue by pierrre** [docker-library/golang#79]
Why alpine images recompile Go from source instead of using the binary distribution?
Is it an issue with libc?

Why alpine images use Go 1.4.3 as boostrap instead of the latest binary distribution (1.5 or 1.6)?

Thank you

**Comment by tianon** [comment]
Yes, the Go binary distributions are dynamically linked against glibc,
which Alpine doesn't have.

Additionally, Go 1.5 and above are written in pure Go and have no C
bootstrap code, so we have to build Go 1.4 in order to build Go 1.5+ with
it.

**Comment by pierrre** [comment]
OK I understand, thank you.

**Comment by pierrre** [comment]
I just had an idea:
Can we install temporarily the `go` package from Alpine Linux (https://pkgs.alpinelinux.org/package/community/x86_64/go)
and use it as a boostrap?

**Comment by pierrre** [comment]
I successfully compiled Go 1.6 with this Dockerfile:
```
FROM alpine:3.3

ENV GOLANG_VERSION 1.6
ENV GOLANG_SRC_URL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz
ENV GOLANG_SRC_SHA256 a96cce8ce43a9bf9b2a4c7d470bc7ee0cb00410da815980681c8353218dcf146

RUN set -ex \
	&& apk add --no-cache --virtual .build-deps \
		bash \
		ca-certificates \
		gcc \
		go \
		musl-dev \
		openssl \
	\
	&& export GOROOT_BOOTSTRAP=/usr/lib/go \
	\
	&& wget -q "$GOLANG_SRC_URL" -O golang.tar.gz \
	&& echo "$GOLANG_SRC_SHA256  golang.tar.gz" | sha256sum -c - \
	&& tar -C /usr/local -xzf golang.tar.gz \
	&& rm golang.tar.gz \
	&& cd /usr/local/go/src \
	&& ./make.bash \
	\
	&& rm -rf /usr/local/go/pkg/bootstrap \
	&& apk del .build-deps

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH
```

**Comment by pierrre** [comment]
BTW, I saw in the build logs that Alpine Linux installed Go 1.5.3 instead of 1.6.
Do you know why?
1.6 is available in the repository: https://pkgs.alpinelinux.org/package/community/x86_64/go

**Comment by client9** [comment]
Hi @pierrre 

I'm curious as to the origin of this:

re:  Can we install temporarily the go package from Alpine Linux (https://pkgs.alpinelinux.org/package/community/x86_64/go) and use it as a bootstrap?

What problem does this solve? Or what advantage does this have over building it form source?  Are the alpine and golang versions out of sync?

thanks!

n

**Comment by pierrre** [comment]
@client9

First, it doesn't "feel right" to always use Go 1.4.3 as a boostrap to build Go 1.6.
Will it work with Go 1.7 or 1.8?

It could also make the build of this base image faster:
- we don't need to download and compile Go 1.4.3
- it's faster to install from the Alpine Linux repository


> What problem does this solve? Or what advantage does this have over building it form source?

See the first post.
Currently, the Golang Alpine Linux image:
- download Go 1.4.3 and compile it from source
- uses Go 1.4.3 as a boostrap to compile Go 1.6 from source

I propose to change the first step, and use the Go package from the Alpine Linux repository as a boostrap to compile Go 1.6 from source.

**Comment by tboerger** [comment]
I would suggest to simply use https://pkgs.alpinelinux.org/package/community/x86_64/go-bootstrap as this is a package used by alpine to build the go packages >= 1.5.

**Comment by tianon** [comment]
As to whether Go 1.4 will stay supported, https://golang.org/doc/install/source#go14 is the current source of truth, and even for 1.6 they still recommend compiling Go 1.4 from source to use as a bootstrap for building Go 1.6 (so there is a very strong case there from upstream directly for keeping the `Dockerfile` as-is).

That being said, I'm not opposed to having our `Dockerfile` install the `go` APK just long enough to compile against it as a bootstrap; that seems pretty sane, especially since we just need "some Go 1.4+".  Upstream is pretty flexible about the bootstrap compiler, and the bits it's needed to compile are fairly minimal.

**Comment by tianon** [comment]
(Probably also worth noting that IIRC, https://pkgs.alpinelinux.org/package/community/x86_64/go points to `edge` packages, but we're using `3.3`; `edge` is Alpine's "development" version, similar to Debian unstable, Ubuntu Devel [currently Xenial], or Fedora rawhide).

**Comment by pierrre** [comment]
:)
