### ISSUE TITLE
golang 1.6 apline is missing git

### ISSUE THREAD

**Issue by DavidJFelix** [docker-library/golang#80]
Git is pretty critical to most go get processing. It's present in the debian version of golang 1.6 but not the alpine version

**Comment by yosifkit** [comment]
> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar).
> - [golang#golangalpine](https://github.com/docker-library/docs/tree/34c211c3f9b997eb1a75f2c1e42bfc6e65692f1d/golang#golangalpine)
>     (source of https://hub.docker.com/_/golang/ description)

To minimize space in your own images, you can do something like the following:
```Dockerfile
RUN apk add --no-cache git mercurial \
    && go get github.com/random/library/that/I/use/ \
    && apk del git mercurial
```

**Comment by DavidJFelix** [comment]
Ah thanks @yosifkit I was trying without `--no-cache` and it didn't work.

**Comment by sourcesoft** [comment]
@yosifkit Just wanted to say I love you

**Comment by guptarohit** [comment]
Thank you @yosifkit

**Comment by hazel-shen** [comment]
Thank you saved my life. @yosifkit
