### ISSUE TITLE
1.5 Go Vendor Experiment

### ISSUE THREAD

**Issue by kf6nux** [docker-library/golang#81]
It would be nice if the onbuild docker image supported 1.5 Go Vendor Experiment.

**Comment by tianon** [comment]
Since `--build-arg`/`ARG` was only added in 1.9.0, what does this mean for backwards compatibility?  Does an image built with an `ARG` layer still work on older Docker engines?

**Comment by kf6nux** [comment]
I thought this was an easier fix than it actually is.

Using `--build-arg` the way I described is probably not the way to go because it would only allow you to create two different golang:onbuild docker images (one supporting vendoring, and the other not).

I'm open to suggestions on the right way to support the 1.5 Go Vendor Experiment in the official docker images.

**Comment by FrenchBen** [comment]
:+1: as I'm running into similar build issues

**Comment by tianon** [comment]
Honestly, I'd actually generally recommend projects _not_ use `:onbuild` except as the catalyst for getting development off the ground really quickly.  I have yet to have a personal project for which my needs don't eventually diverge from the basic bare-minimum functionality `:onbuild` provides.

**Comment by kf6nux** [comment]
Closing as 1.6 is now out making this issue stale.
