### ISSUE TITLE
Feature request: "development" tag

### ISSUE THREAD

**Issue by kop** [docker-library/golang#88]
Hi,

I have a proposal for this image that, as I believe, will improve Go development experience a lot.
I'm talking about hot code reloading. I'm not sure if it will work good for big projects, but for my use case which is tons of small Go apps, it will be a huge time saver.

Implementation should not be complicated, all we need to do is to add some file system watcher that will trigger builds after `*.go` file changes and restart app after successful builds.

**Comment by tianon** [comment]
I love the idea, but I think it probably ought to be implemented under another namespace -- we try to stick to being as "vanilla" as we can, keeping with the spirit of upstream (and their documented and supported methods) as closely as possible.  With automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links), it's reasonably easy to have an up-to-date image built `FROM` this one. :+1:

**Comment by kop** [comment]
@tianon, I wanted to create it as a separate image from the start but just thought it may be easier for everyone to have such feature in official image (that every dev will visit) instead of searching across the tons of projects in Docker Hub.

**Comment by tianon** [comment]
Coming back four years later (:exclamation:), and my thoughts on this are still consistent with https://github.com/docker-library/golang/issues/88#issuecomment-192042697 -- I think this is an interesting idea, but the official images is unfortunately not the appropriate place for it (unless it becomes an official "distribution" of the Go project, in which case we would follow suit). :bow: :heart:
