### ISSUE TITLE
Go 1.7 Beta image for Docker

### ISSUE THREAD

**Issue by jadbox** [docker-library/golang#94]
https://groups.google.com/forum/#!msg/golang-nuts/zndSPkE2DVE/bcOu35-OBwAJ

**Comment by jadbox** [comment]
I see that in master that there's a Dockerfile for it, but it's not listed on the Dockerhub tags pages:
https://hub.docker.com/r/library/golang/tags/

**Comment by tianon** [comment]
https://github.com/docker-library/golang/blob/ca728c5e13b90088d0b48aaf4108bbe31838d8d1/README.md

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/golang" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/golang), especially [PRs with the "library/golang" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fgolang). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

If you'd like to help out, feel free to clone the repo locally and use the output of `./generate-stackbrew-library.sh` to send a PR to [`github.com/docker-library/official-images`'s](https://github.com/docker-library/official-images) `library/golang` file. :+1:  (if you don't before then, either myself or @yosifkit will likely do so tomorrow)

**Comment by jadbox** [comment]
@tianon Thanks! I'm remote atm and couldn't run `generate-stackbrew-library.sh`, but I did do this PR by raw (mobile) text changes:
https://github.com/jadbox/official-images/pull/1

Let me know if it would be better to close this task and move conversation to the PR (or vice-versa if the PR isn't ideal).

**Comment by pwaller** [comment]
Done https://github.com/docker-library/official-images/pull/1797

**Comment by jadbox** [comment]
Thanks @pwaller 

I didn't see while working on mobile that my PR was made against my _own_ master branch. hah ><
