### ISSUE TITLE
golang:1.x-alpine have no /etc/ssl

### ISSUE THREAD

**Issue by capkurmagati** [docker-library/golang#96]
How to reproduce it:
```
$ docker run --rm golang:1.6.2-alpine ls /etc/ssl
ls: /etc/ssl: No such file or directory
```
It also happens with `1.5-alpine` and `1.7-alpine`.
I think it relates to https://github.com/docker-library/golang/commit/f3768925fd0ebeb966c30bc64206b0e6020de66e.

Because I built the image from https://github.com/docker-library/golang/commit/0ce80411b9f41e9c3a21fc0a1bffba6ae761825a and `/etc/ssl` existed.

I am not sure if this is a expected behavior but one builds project which send `https` request will get `x509: failed to load system roots and no roots provided`.

How about adding `RUN apk add ca-certificates` to Dockerfile or using another tag?
I would like to create a pull request.

**Comment by capkurmagati** [comment]
@tianon Could you check on this please.

**Comment by tianon** [comment]
IMO this is by design; from the [Docker Hub description (under `golang:alpine`)](https://hub.docker.com/_/golang/):

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Comment by capkurmagati** [comment]
@tianon I know alpine is the minimum environment. 
But what I want to address is that `/etc/ssl` (ca-certificates) disappears after https://github.com/docker-library/golang/commit/f3768925fd0ebeb966c30bc64206b0e6020de66e which will cause problems.
Images builds on this image will change its behaviour even if the Dockerfile remains the same.
Sorry for my broken English.

**Comment by yosifkit** [comment]
The `ca-certificates` package has been removed since the alpine variant was introduced in #68.  There is a change in alpine 3.4 that fixes the removal of `/etc/ssl`: https://bugs.alpinelinux.org/issues/5382, so it is the change to `alpine:3.4` that has caused our intended behavior to finally reflect in the images.
